// Purpose-built verification command. Uses an isolated profile and synthetic credentials only.
exports.run=async({app,win,fs,path,state,credential,entry})=>{
  const errors=[];win.webContents.on('console-message',(event,level,message)=>{if(event.level==='error'||level===3)errors.push(event.message||message)})
  await new Promise(resolve=>win.webContents.once('did-finish-load',resolve))
  const passed=[]
  const pause=ms=>new Promise(r=>setTimeout(r,ms)),check=(ok,msg)=>{if(!ok)throw new Error(msg);passed.push(msg);fs.writeFileSync(path.join(app.getPath('userData'),'verification-progress.json'),JSON.stringify({lastCheck:msg,count:passed.length},null,2))}
  await pause(1000)
  if(app.commandLine.hasSwitch('verify-closed-pipe')){process.stdout.write('Closed output pipe regression check\n');process.stderr.write('Closed error pipe regression check\n');await pause(100)}
  check((await win.webContents.executeJavaScript('document.body.innerText')).includes('先了解你的运动基础'),'Chinese first-launch profile')
  const synthetic='verification-only-not-a-real-api-key'
  await win.webContents.executeJavaScript(`window.xunlianDesktop.credentialSet(${JSON.stringify(synthetic)})`)
  check(await win.webContents.executeJavaScript(`window.xunlianDesktop.credentialGet().then(v=>v===${JSON.stringify(synthetic)})`),'Credential round-trip')
  check(!fs.readFileSync(credential).includes(Buffer.from(synthetic)),'Credential encryption')
  await win.webContents.executeJavaScript("window.xunlianDesktop.stateSave({routines:[],workouts:[],bodyweight:[],customEx:[],week:{},dayPlan:{},schemaVersion:2,verificationMarker:'saved',apiKey:'must-not-be-saved'})")
  check(!fs.readFileSync(state,'utf8').includes('must-not-be-saved'),'State credential exclusion')
  check((await win.webContents.executeJavaScript("window.xunlianDesktop.stateLoad().then(v=>v.verificationMarker)"))==='saved','State round-trip')
  const fixture=JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'workout-fixture.json'),'utf8'))
  await win.webContents.executeJavaScript(`window.xunlianDesktop.stateSave(${JSON.stringify(fixture)}).then(()=>{localStorage.setItem('gym_state_v1',${JSON.stringify(JSON.stringify(fixture))});location.hash='#/workout';location.reload()})`)
  await new Promise(resolve=>win.webContents.once('did-finish-load',resolve));await pause(1000)
  check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).some(b=>b.textContent.includes('预填剩余组'))"),'Prefill button visible')
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('预填剩余组')).click()",true)
  const copied=await win.webContents.executeJavaScript("JSON.parse(localStorage.getItem('gym_state_v1')).active.entries[0].sets")
  check(copied[0].done&&copied[0].r===8&&copied[2].w===15&&copied[2].r===10&&!copied[2].done,'Prefill preserves actual records')
  check((await win.webContents.executeJavaScript('document.body.innerText')).includes('120 s'),'Source rest preset visible')
  await win.webContents.executeJavaScript("document.querySelector('.setrow [role=checkbox][aria-checked=false]').click()",true);await pause(300)
  check(await win.webContents.executeJavaScript("['2:00','1:59'].includes(document.querySelector('#timer.rest .t')?.textContent)"),'Source 120-second rest countdown')
  await win.webContents.executeJavaScript("document.querySelector('.setrow [role=checkbox][aria-checked=false]').click()",true);await pause(300)
  check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('h3')).some(h=>h.textContent.includes('杠铃卧推')&&/barbell bench press/i.test(h.textContent)&&h.textContent.includes('完成'))"),'Bilingual completion sheet')
  check(await win.webContents.executeJavaScript("document.querySelector('.sheet .bw-read')?.textContent.trim()==='15 kg'&&document.body.innerText.includes('下次按来源方案')"),'Actual working load is not replaced by lifetime best')
  await pause(500)
  fs.writeFileSync(path.join(app.getPath('userData'),'workout-completion.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('保存并下')).click()",true)
  check(await win.webContents.executeJavaScript("JSON.parse(localStorage.getItem('gym_state_v1')).active.cur===1"),'Completion advances to next exercise')
  for(const [route,title] of [['nutrition','营养'],['nutrition/week','一周餐食'],['programs','训练计划资料库'],['planning','统一规划档案'],['joint','训练与饮食联合周计划'],['library','动作库'],['assistant','AI 训练与饮食教练'],['health','心率与健康数据'],['kitchen','HowToCook 在线菜谱'],['settings','设置']]){
    await win.webContents.executeJavaScript(`location.hash=${JSON.stringify('#/'+route)}`)
    let text=''
    for(let attempt=0;attempt<40;attempt++){await pause(250);text=await win.webContents.executeJavaScript('document.body.innerText');if(text.includes(title))break}
    check(!text.includes('Something went wrong')&&!text.includes('出了点问题'),'Route crashed: '+route+' '+errors.join('; '))
    check(text.includes(title),'Missing title: '+route+' '+text.slice(0,120))
    if(route==='programs'){
      check(await win.webContents.executeJavaScript("document.querySelectorAll('.source-card').length===8&&document.querySelectorAll('.template-card').length===0&&document.querySelectorAll('.program-filters select').length===4"),'Knowledge sources first, four filters, no flat plan pile');
      win.webContents.enableDeviceEmulation({screenPosition:'mobile',screenSize:{width:360,height:800},viewPosition:{x:0,y:0},viewSize:{width:360,height:800},deviceScaleFactor:1,scale:1});await pause(200)
      fs.writeFileSync(path.join(app.getPath('userData'),'program-sources-mobile.png'),(await win.webContents.capturePage({x:0,y:0,width:360,height:800})).toPNG())
      await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.source-card')).find(b=>b.textContent.includes('ACSM 2026')).click()",true);await pause(200)
      check(await win.webContents.executeJavaScript("document.querySelectorAll('.category-card').length>0&&document.querySelectorAll('.template-card').length===0&&location.hash.includes('source=acsm')"),'Source opens categories and keeps a back-navigation history entry')
      await win.webContents.executeJavaScript("document.querySelector('.category-card').click()",true);await pause(200)
      check(await win.webContents.executeJavaScript("document.querySelectorAll('.template-card').length===3&&location.hash.includes('category=')"),'Category opens its three ACSM plans')
      await win.webContents.executeJavaScript("document.querySelector('.template-card').click()",true);await pause(300)
      check(await win.webContents.executeJavaScript("document.body.innerText.includes('训练预填')&&document.body.innerText.includes('180 s')&&document.body.innerText.includes('80% 1RM')"),'Official-derived program prescription review')
      check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.prescription-grid input')).every(i=>{const c=getComputedStyle(i),r=i.getBoundingClientRect();return c.color==='rgb(255, 255, 255)'&&c.backgroundColor!=='rgb(255, 255, 255)'&&r.width>=90&&r.right<=innerWidth})"),'Readable dark numeric fields at 360px')
      check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.prescription-grid')).every(g=>Array.from(g.querySelectorAll('label')).find(l=>l.textContent.includes('重量'))?.querySelector('input').value.trim()!=='')"),'Preset load is prefilled in the editable numeric field')
      await win.webContents.executeJavaScript("document.querySelector('.prescription-grid').scrollIntoView({block:'center'})");await pause(200)
      fs.writeFileSync(path.join(app.getPath('userData'),'program-dark-mobile.png'),(await win.webContents.capturePage()).toPNG())
      await win.webContents.executeJavaScript("document.documentElement.dataset.theme='light'")
      check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.prescription-grid input')).every(i=>getComputedStyle(i).color!=='rgb(255, 255, 255)')"),'Readable light numeric fields')
      await win.webContents.executeJavaScript("document.documentElement.dataset.theme='dark'")
      await win.webContents.executeJavaScript("document.querySelector('.mback').click()",true)
  win.webContents.disableDeviceEmulation()
    }
    if(route==='settings'){
      await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='显示密钥').click()",true)
      check(await win.webContents.executeJavaScript("document.querySelector('input[placeholder=\"输入 API 密钥\"]')?.type==='text'"),'Credential reveal avoids password keyboard')
    }
  }
  // Mock traffic: short intake and local portion arithmetic, never real keys.
  win.webContents.enableDeviceEmulation({screenPosition:'mobile',screenSize:{width:360,height:800},viewPosition:{x:0,y:0},viewSize:{width:360,height:800},deviceScaleFactor:1,scale:1})
  check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.credential-actions .btn')).every(b=>{const r=b.getBoundingClientRect();return r.width>=120&&r.height>=44&&r.height<70&&r.right<=innerWidth})"),'Compact mobile credential actions')
  await win.webContents.executeJavaScript("document.querySelector('.deepseek-settings').scrollIntoView({block:'start'})");await pause(200)
  fs.writeFileSync(path.join(app.getPath('userData'),'settings-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript(`window.__originalFetch=window.fetch;window.fetch=async(url,options)=>{if(String(url)!=='https://api.deepseek.com/chat/completions')return window.__originalFetch(url,options);const body=JSON.parse(options.body);let content='OK';if(body.messages[0].role==='system'){const input=JSON.parse(body.messages.find(m=>m.role==='user').content);if(body.messages[0].content.includes('当前操作是理解需求'))content=JSON.stringify({questions:input.answers||window.__directCoach?[]:[{question:'有没有伤病、需要避开的动作或忌口？'}],summary:'使用已有资料，只补问限制',profile:{trainingPlace:'gym',trainingDays:3,availableDays:[1,3,5],trainingDuration:60,limitations:'无',allergies:'无'},assumptions:['未指定星期，建议周一三五，可修改']});else content=JSON.stringify({program:{nameZh:'模拟联合计划',days:input.context.availableDays.map(weekday=>({weekday,dayName:'模拟训练日',exerciseItems:[{originalText:input.exercises.find(e=>e.nameEn==='barbell bench press').nameEn,sets:2,reps:10,restSec:90,weight:null}]}))},meals:input.dates.flatMap(date=>input.feasibleDayMenu.map(m=>({...m,date,servings:m.servings*.25}))),explanation:'模拟响应验证，份数故意偏低，检查程序校准'});}return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content}}]}),{status:200,headers:{'Content-Type':'application/json'}})};void 0`)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='测试连接').click()",true);await pause(250)
  check((await win.webContents.executeJavaScript('document.body.innerText')).includes('连接成功'),'Mock connection succeeds')
  await win.webContents.executeJavaScript("location.hash='#/assistant'");await pause(500)
  await win.webContents.executeJavaScript("(()=>{const field=document.querySelector('textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,'早上六点半到健身房，九点上班，请安排训练和早餐');field.dispatchEvent(new Event('input',{bubbles:true}));})()");await pause(100)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='生成训练与饮食方案').click()",true);await pause(500)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('textarea[placeholder=\"已有条件不用重填，没有限制请写无\"]').length===1&&!document.body.innerText.includes('以上限制和忌口已确认')"),'One necessary question, no repeated form or confirmation')
  fs.writeFileSync(path.join(app.getPath('userData'),'coach-intake-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("(()=>{const field=document.querySelector('textarea[placeholder=\"已有条件不用重填，没有限制请写无\"]');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,'无');field.dispatchEvent(new Event('input',{bubbles:true}));})()");await pause(100)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='回答完了，直接生成').click()",true)
  let coachText='';for(let i=0;i<60;i++){await pause(250);coachText=await win.webContents.executeJavaScript('document.body.innerText');if(coachText.includes('审核训练与饮食'))break}
  check(coachText.includes('审核训练与饮食')&&coachText.includes('校准'),'Short intake and bad portions produce calibrated seven-day proposal: '+coachText.slice(-500))
  await win.webContents.executeJavaScript("location.hash='#/home'");await pause(300)
  await win.webContents.executeJavaScript("location.hash='#/assistant'");await pause(500)
  check((await win.webContents.executeJavaScript('document.body.innerText')).includes('模拟联合计划'),'Coach proposal survives reopening')
  await win.webContents.executeJavaScript("window.__directCoach=true;Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='生成训练与饮食方案').click()",true)
  for(let i=0;i<60;i++){await pause(250);coachText=await win.webContents.executeJavaScript('document.body.innerText');if(coachText.includes('审核训练与饮食'))break}
  check(coachText.includes('审核训练与饮食')&&!coachText.includes('回答完了，直接生成'),'Sufficient conditions skip questions')
  await require('./verify-plan-layout.cjs').run({win,check,pause,fs,path,app})
  await win.webContents.executeJavaScript("window.fetch=window.__originalFetch;document.querySelector('.feature-page').scrollIntoView({block:'start'})");await pause(200)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.day-plans').length===2&&document.querySelectorAll('.day-track').length===2"),'Training and meals use independent date carousels')
  await win.webContents.executeJavaScript("document.querySelector('.day-plans .day-dates button:nth-child(2)').click()",true);await pause(650)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.day-plans')[0].querySelector('.day-dates button[aria-pressed=true]').textContent.includes('周二')&&document.querySelectorAll('.day-plans')[1].querySelector('.day-dates button[aria-pressed=true]').textContent.includes('周一')"),'Training date change preserves independently selected food date')
  check(await win.webContents.executeJavaScript("document.querySelector('.day-track').getBoundingClientRect().height<180&&document.documentElement.scrollWidth<=innerWidth"),'Rest-day carousel shrinks rather than retaining longest training day')
  await win.webContents.executeJavaScript("document.querySelector('.day-plans .day-dates button:first-child').click()",true);await pause(650)
  fs.writeFileSync(path.join(app.getPath('userData'),'assistant-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.seg button')).find(b=>b.textContent==='饮食计划')?.click()",true);await pause(300)
  fs.writeFileSync(path.join(app.getPath('userData'),'assistant-food-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='食材与完整做法'&&b.offsetWidth>0).click()",true);await pause(250)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.recipe-ingredient').length>0&&document.querySelectorAll('.recipe-guide .steps-list li').length>=4"),'Recipe ingredients and detailed cooking steps reachable from coach')
  fs.writeFileSync(path.join(app.getPath('userData'),'recipe-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='开始逐步做菜').click()",true);await pause(100)
  const firstCookingStep=await win.webContents.executeJavaScript("document.querySelector('.cooking-current').textContent")
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='下一步').click()",true);await pause(100)
  check(await win.webContents.executeJavaScript("document.querySelector('.cooking-current').textContent!=="+JSON.stringify(firstCookingStep)),'Step-by-step cooking advances')
  await win.webContents.executeJavaScript("document.querySelector('.mback').click()",true);await pause(100)
  await win.webContents.executeJavaScript("(()=>{const saved=JSON.parse(localStorage.getItem('gym_state_v1'));saved.xunlian.meals=saved.xunlian.proposals.find(p=>p.origin==='assistant').snapshots;localStorage.setItem('gym_state_v1',JSON.stringify(saved));return window.xunlianDesktop.stateSave(saved).then(()=>{location.hash='#/nutrition/week';location.reload()})})()")
  await new Promise(resolve=>win.webContents.once('did-finish-load',resolve));await pause(600)
  win.webContents.enableDeviceEmulation({screenPosition:'mobile',screenSize:{width:360,height:800},viewPosition:{x:0,y:0},viewSize:{width:360,height:800},deviceScaleFactor:1,scale:1})
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='购物清单').click()",true);await pause(100)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.shopping-item').length>0"),'Shopping ingredients are separate checklist rows')
  check(await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('.shopping-item')).every(row=>{const r=row.getBoundingClientRect();return r.width>=280&&r.right<=innerWidth&&row.querySelector('input').getBoundingClientRect().width>=24})"),'Readable purchasing rows at 360px')
  await win.webContents.executeJavaScript("document.querySelector('.shopping-item input').click()",true);await pause(300)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.shopping-item.purchased').length===1"),'Purchased item moves to completed')
  fs.writeFileSync(path.join(app.getPath('userData'),'shopping-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("location.reload()")
  await new Promise(resolve=>win.webContents.once('did-finish-load',resolve));await pause(600)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='购物清单').click()",true);await pause(100)
  check(await win.webContents.executeJavaScript("document.querySelectorAll('.shopping-item.purchased').length===1"),'Purchase checklist survives reload')
  await win.webContents.executeJavaScript("location.hash='#/nutrition'");await pause(500)
  await win.webContents.executeJavaScript("window.__beforePortion=JSON.parse(localStorage.getItem('gym_state_v1')).xunlian;document.querySelector('.recipe-actions button:last-child').click()",true);await pause(200)
  await win.webContents.executeJavaScript("(()=>{const input=document.querySelector('.sheet input'),set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(input,String(Number(input.value)*1.2));input.dispatchEvent(new Event('input',{bubbles:true}))})()",true);await pause(150)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='保存计划份数').click()",true);await pause(250)
  check(await win.webContents.executeJavaScript("(()=>{const x=JSON.parse(localStorage.getItem('gym_state_v1')).xunlian;return x.logs.length===window.__beforePortion.logs.length&&JSON.stringify(x.meals)!==JSON.stringify(window.__beforePortion.meals)})()"),'Editing planned portions changes the plan without recording eaten food')
  await win.webContents.executeJavaScript("location.hash='#/nutrition/photo'");await pause(500)
  win.webContents.enableDeviceEmulation({screenPosition:'mobile',screenSize:{width:360,height:800},viewPosition:{x:0,y:0},viewSize:{width:360,height:800},deviceScaleFactor:1,scale:1})
  await win.webContents.executeJavaScript(`window.__beforePhoto=JSON.parse(localStorage.getItem('gym_state_v1')).xunlian.meals;window.__photoFetch=window.fetch;window.fetch=async(url,options)=>{if(String(url)!=='https://api.deepseek.com/chat/completions')return window.__photoFetch(url,options);const body=JSON.parse(options.body),content=body.messages.find(m=>m.role==='user').content;window.__photoHasImage=Array.isArray(content)&&content.some(c=>c.type==='image_url');const input=JSON.parse(content[0].text),food=input.foods.find(f=>f.nameZh==='猪里脊');return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({status:'identified',nameZh:'模拟餐食估算',confidence:'low',notes:['合成图片和模拟响应，只验证流程'],ingredients:[{foodId:food.id,grams:100,gramsMin:80,gramsMax:130,basis:'合成分量估计'}]})}}]}),{status:200,headers:{'Content-Type':'application/json'}})};void 0`)
  const chooseSyntheticPhoto=async()=>{await win.webContents.executeJavaScript("new Promise(resolve=>{const canvas=document.createElement('canvas');canvas.width=120;canvas.height=90;canvas.getContext('2d').fillRect(0,0,120,90);canvas.toBlob(blob=>{const input=document.querySelector('.photo-pickers input'),dt=new DataTransfer();dt.items.add(new File([blob],'synthetic-meal.png',{type:'image/png'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));resolve()},'image/png')})");await pause(300)}
  const analyzePhoto=async()=>{await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='识别并记录实际摄入').click()",true);for(let i=0;i<30;i++){await pause(200);if(await win.webContents.executeJavaScript("document.body.innerText.includes('模拟餐食估算 · 已记录')"))return}throw new Error('Photo recognition did not finish')}
  await chooseSyntheticPhoto();await analyzePhoto();await pause(300)
  check(await win.webContents.executeJavaScript("window.__photoHasImage&&JSON.parse(localStorage.getItem('gym_state_v1')).xunlian.logs.length===1&&JSON.stringify(JSON.parse(localStorage.getItem('gym_state_v1')).xunlian.meals)===JSON.stringify(window.__beforePhoto)"),'Photo vision payload and automatic intake, original plan preserved pending choice')
  fs.writeFileSync(path.join(app.getPath('userData'),'photo-mobile.png'),(await win.webContents.capturePage()).toPNG())
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='只记录已吃，保留计划').click()",true);await pause(100)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='继续记录下一餐').click()",true);await pause(100)
  await chooseSyntheticPhoto();await analyzePhoto()
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='替换该餐计划').click()",true);await pause(350)
  check(await win.webContents.executeJavaScript("(()=>{const x=JSON.parse(localStorage.getItem('gym_state_v1')).xunlian,last=x.logs.at(-1),before=window.__beforePhoto.filter(m=>m.date!==last.date||m.slot!==last.slot),after=x.meals.filter(m=>m.date!==last.date||m.slot!==last.slot);return x.logs.length===2&&last.plannedMealId&&JSON.stringify(before)===JSON.stringify(after)&&x.meals.some(m=>m.id===last.plannedMealId)&&!JSON.stringify(x).includes('data:image')})()"),'Explicit replacement only changes selected meal and never duplicates actual intake or stores image')
  await win.webContents.executeJavaScript("window.fetch=window.__photoFetch;location.hash='#/planning'");await pause(500)
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='计算建议目标').click()",true);await pause(200)
  check(await win.webContents.executeJavaScript("document.body.innerText.includes('基础代谢预测')&&document.body.innerText.includes('全天消耗预测（含训练）')&&document.body.innerText.includes('官方依据与计算适用范围')"),'Nutrition separates basal expenditure, daily energy and official source references')
  await win.webContents.executeJavaScript("Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='保存档案与目标').click()",true);await pause(250)
  check(await win.webContents.executeJavaScript("document.querySelector('.balance-notice')&&JSON.parse(localStorage.getItem('gym_state_v1')).xunlian.balanceNotices.length>0"),'Dynamic rebalancing informs the user immediately')
  win.webContents.disableDeviceEmulation()
  const manifest=JSON.parse(fs.readFileSync(path.join(path.dirname(entry),'media-manifest.json'),'utf8'))
  const crypto=require('node:crypto')
  for(const m of manifest.files){const file=fs.readFileSync(path.join(path.dirname(entry),m.path));check(file.length===m.bytes,'Media size: '+m.path);check(crypto.createHash('sha256').update(file).digest('hex')===m.sha256,'Media hash: '+m.path)}
  const hq=JSON.parse(fs.readFileSync(path.join(path.dirname(entry),'exercise-hq-manifest.json'),'utf8'));for(const m of hq.files){check(crypto.createHash('sha256').update(fs.readFileSync(path.join(path.dirname(entry),m.path))).digest('hex')===m.sha256,'Higher-resolution media hash')}
  await win.webContents.executeJavaScript("location.hash='#/library'");await pause(600)
  await pause(500)
  check(await win.webContents.executeJavaScript('Array.from(document.images).some(img=>img.complete&&img.naturalWidth>0&&img.src.includes("/img/"))'),'Offline exercise image decode')
  await win.webContents.executeJavaScript("window.xunlianDesktop.credentialSet('')")
  check(!errors.length,'Renderer errors: '+errors.join('; '))
  const report={status:'PASS',checkedAt:new Date().toISOString(),platform:process.platform,packaged:app.isPackaged,checks:['Chinese first-launch profile','DPAPI credential round-trip and encrypted file','State IPC round-trip and credential redaction','Prefill preserves actual records','Source 120-second rest preset and countdown','Bilingual completion sheet','Completion advances to next exercise','Ten offline routes','2648 original media and 22 higher-resolution photo SHA-256 hashes','Readable dark/light program numeric fields at 360px','Credential visibility toggle','Compact mobile credential actions','Mock short intake, direct generation, local portion calibration and saved proposal','Recipe ingredients, detailed steps and step-by-step cooking','Separate persistent shopping checklist','Planned portion editing never records actual intake','Independent date card navigation and compact rest-day height','Photo image request, automatic estimated intake and explicit single-meal replacement','Official nutrition basis and energy display','Three-level source/category/plan browser with four filters and numeric load prefill','Full-width nutrition summary; no single-character lines at 320/360/412px with enlarged text','Continuous date change and rightward touch swipe without resize snapping','Apply action stays above bottom navigation at page end','Dynamic balance notice and retained actual records','Offline exercise image decoding'],rendererErrors:errors,profile:'isolated verification profile; synthetic workout'}
  fs.writeFileSync(path.join(app.getPath('userData'),'verification-report.json'),JSON.stringify(report,null,2));app.quit()
}
