import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { allExercises,exerciseName } from '../lib/exercises.js'
import { allFoods,allRecipes,nutritionLine } from './Nutrition.jsx'
import { clone,planningContext,targets,validateTarget,monday,dateKeys,recipeNutrition,dailyTotals } from '../lib/nutrition.js'
import { eligibleRecipes,validateMeals,applyJoint,ALLERGENS } from '../lib/planning-engine.js'
import { coachCatalog,checkCoachProgram,feasibleMenu,mapCoachProgram,selectCoachCandidates } from '../lib/assistant-plan.js'
import { createDeepSeek } from '../lib/deepseek.js'
import { getCredential } from '../lib/credentials.js'
import { requireAI,aiErrorMessage } from '../lib/ai-errors.js'
import { useAIRequest } from '../lib/useAIRequest.js'
import { uid } from '../lib/format.js'
import guides from '../data/china-guides.json'
import { Section,Row,Button,TextField,TextArea,NumberField,SelectRow,Switch } from '../components/ui.jsx'
import { ProgramReview } from './Programs.jsx'
const weekdays=[{value:1,label:'周一'},{value:2,label:'周二'},{value:3,label:'周三'},{value:4,label:'周四'},{value:5,label:'周五'},{value:6,label:'周六'},{value:0,label:'周日'}]
export default function Assistant(){
  const S=useStore(s=>s.S),update=useStore(s=>s.update),nav=useNavigate(),ai=useAIRequest(),[request,setRequest]=useState(''),[intake,setIntake]=useState(null),[answers,setAnswers]=useState({}),[profile,setProfile]=useState({...clone(S.xunlian.profile),trainingPlace:'gym',availableDays:[1,3,5],trainingDays:3,trainingDuration:45,avoidExercises:'',homeEquipment:[],lowImpact:true}),[confirmed,setConfirmed]=useState(false),[proposal,setProposal]=useState(null),[error,setError]=useState(''),[modification,setModification]=useState('')
  const foods=allFoods(S),recipes=eligibleRecipes(allRecipes(S),foods,profile).slice(0,40),candidates=coachCatalog(allExercises(S),profile),dates=proposal?.dates||dateKeys(monday()),change=(k,v)=>{setProfile({...profile,[k]:v});setConfirmed(false);setProposal(null)}
  const ask=()=>ai.run(async signal=>{setError('');try{requireAI(S);const response=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('intake',{task:'Ask brief clarifying questions for ONE training and meal plan. Do not create the plan yet. Confirm exercise avoidance/injuries, allergies/dislikes, training environment, available days and time. Ask additional questions relevant to the request. Do not promise rapid weight loss.',request,profile:planningContext(S)},{signal});setIntake(response);setProposal(null);setAnswers({});setConfirmed(false);if(/减脂|减重|瘦|lose|fat/i.test(request))setProfile(p=>({...p,goal:'lose'}));else if(/增肌|增重|gain|muscle/i.test(request))setProfile(p=>({...p,goal:'gain'}))}catch(e){setError(aiErrorMessage(e))}})
  const generate=()=>ai.run(async signal=>{setError('');try{requireAI(S);if(!confirmed||intake.questions.some((_,i)=>!answers[i]?.trim()))throw new Error('请回答追问，并确认运动限制和忌口。')
    if(!Number.isInteger(profile.age)||profile.age<18||profile.age>65)throw new Error('此自动训练与饮食编排面向 18–65 岁成年人；请使用手动或专业指导方案。')
    if(profile.specialDiet)throw new Error('特殊医疗或孕期需求请先使用专业指导方案，不生成普通成人计划。')
    if(!Number.isInteger(profile.trainingDays)||profile.trainingDays<1||profile.trainingDays>6||profile.availableDays.length!==profile.trainingDays)throw new Error('请勾选与每周训练天数相同数量的星期。')
    let target=S.xunlian.target&&profile.goal===S.xunlian.profile.goal?clone(S.xunlian.target):targets(profile,profile.weightKg);validateTarget(target)
    if(!recipes.length||!candidates.length)throw new Error('当前限制下没有足够的可用动作或完整营养食谱，请修改限制或先补充数据。')
    const menu=feasibleMenu(recipes,foods,target);if(!menu)throw new Error('可用食谱无法满足当前营养目标，请先补充食谱或调整目标。')
    const supplied=selectCoachCandidates(candidates),previous=proposal?{program:proposal.program,meals:proposal.meals}:null,context={...profile,target}
    const input={task:'Create an editable personal TRAINING PROGRAM AND 7-day MEAL PLAN together. Use only supplied exercises, originalText must exactly equal candidate English name (or Chinese name). New program loads must be null; app presets trial loads from confirmed fitness level/history. Every date must include breakfast/lunch/dinner. Only provided recipe IDs. Daily kcal within 20% and protein within 30% (minimum tolerance 20g) of target. Respect allowed weekdays, exercise exclusions, low impact and equipment. Fitness guide exercise choices are app-authored, not an official fixed course. Explain progression and recovery. Do not promise rapid loss. Return program and meals, never merely a template ID.',request,answers:intake.questions.map((question,i)=>({question,answer:answers[i]})),context,dates,exercises:supplied.map(e=>({nameEn:e.nameEn||e.n,nameZh:e.nameZh,equipment:e.eq,muscle:e.tg,type:e.bp})),recipes:recipes.map(r=>({id:r.id,name:r.nameZh,ingredients:r.ingredients.map(i=>foods.find(f=>f.id===i.foodId)?.nameZh),nutrition:recipeNutrition(r,foods).nutrition})),feasibleDayMenu:menu,guides,previous,modification}
    let program,snapshots
    const result=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('coach',input,{signal,validate:data=>{program=mapCoachProgram(data.program,supplied,uid(),S.xunlian.revision);checkCoachProgram(program,candidates,profile);snapshots=validateMeals(data,dates,recipes,foods,profile,target,uid)}})
    setProposal({kind:'joint',id:uid(),...result,program,target,snapshots,dates,profile:clone(profile),baseRevision:S.xunlian.revision,createdAt:Date.now()});setModification('')
  }catch(e){setError(e.code?aiErrorMessage(e):e.message)}})
  const apply=()=>{setError('');try{checkCoachProgram(proposal.program,candidates,profile);const snapshots=validateMeals(proposal,proposal.dates,recipes,foods,profile,proposal.target,uid);update(s=>{applyJoint(s,{...proposal,snapshots,profile:{...proposal.profile,onboardingCompleted:true}},{training:true,meals:true,target:true,profile:true},allExercises(s),uid)});useUI.getState().toast('训练与饮食计划已应用');nav('/plan')}catch(e){setError(e.message)}}
  return <div className="narrow"><h1>AI 训练与饮食教练</h1><p className="sect-f">先说目标，教练追问限制，再用本机真实动作和食谱编排。确认前不会改变正在使用的计划。</p><TextArea maxLength={3000} value={request} placeholder="例如：我想减脂，给我健身房的训练计划和配套饮食" onChange={e=>setRequest(e.target.value)}/><Button variant="primary" disabled={ai.busy||!request.trim()} onClick={ask}>开始对话，确认需求</Button><Button onClick={()=>nav('/settings')}>AI 连接设置</Button>
    {intake&&<><Section title="教练先了解一下" footer={intake.summary}>{intake.questions.map((question,i)=><div className="card" key={i}><p>{question}</p><TextField value={answers[i]||''} placeholder="请明确回答，没有请写“无”" onChange={e=>{setAnswers({...answers,[i]:e.target.value});setConfirmed(false);setProposal(null)}}/></div>)}</Section><Section title="确认训练与饮食条件">
      {[['age','年龄'],['heightCm','身高（厘米）'],['weightKg','体重（公斤）']].map(([key,label])=><Row key={key} title={label}><NumberField nullable value={profile[key]} onChange={v=>change(key,v)}/></Row>)}<SelectRow title="性别（营养估算）" value={profile.sex||''} onChange={v=>change('sex',v)} options={[{value:'',label:'请选择'},{value:'male',label:'男'},{value:'female',label:'女'}]}/><SelectRow title="场地" value={profile.trainingPlace} onChange={v=>change('trainingPlace',v)} options={[{value:'gym',label:'健身房'},{value:'home',label:'居家'}]}/>{profile.trainingPlace==='home'&&['dumbbell','band','kettlebell'].map((eq,i)=><Row key={eq} title={['有哑铃','有弹力带','有壶铃'][i]}><Switch checked={profile.homeEquipment.includes(eq)} onChange={v=>change('homeEquipment',v?[...profile.homeEquipment,eq]:profile.homeEquipment.filter(x=>x!==eq))}/></Row>)}
      <Row title="每周训练天数"><NumberField decimal={false} value={profile.trainingDays} onChange={v=>change('trainingDays',v)}/></Row>{weekdays.map(day=><Row key={day.value} title={day.label}><Switch checked={profile.availableDays.includes(day.value)} onChange={v=>change('availableDays',v?[...profile.availableDays,day.value]:profile.availableDays.filter(x=>x!==day.value))}/></Row>)}<Row title="单次分钟"><NumberField value={profile.trainingDuration} onChange={v=>change('trainingDuration',v)}/></Row>
      <Row title="优先低冲击，避免跑跳"><Switch checked={profile.lowImpact} onChange={v=>change('lowImpact',v)}/></Row><TextField value={profile.avoidExercises} placeholder="禁止的动作，用顿号分隔，例如深蹲、跑步" onChange={e=>change('avoidExercises',e.target.value)}/><TextField value={profile.limitations||''} placeholder="伤病或身体限制，没有填无" onChange={e=>change('limitations',e.target.value)}/><TextField value={profile.allergies||''} placeholder="过敏和忌口，没有填无" onChange={e=>change('allergies',e.target.value)}/><TextField value={profile.dislikedFoods||''} placeholder="不喜欢的食物，没有填无" onChange={e=>change('dislikedFoods',e.target.value)}/>{ALLERGENS.map(a=><Row key={a} title={'排除 '+a}><Switch checked={(profile.excludedAllergens||[]).includes(a)} onChange={v=>change('excludedAllergens',v?[...(profile.excludedAllergens||[]),a]:(profile.excludedAllergens||[]).filter(x=>x!==a))}/></Row>)}
      <SelectRow title="体重目标" value={profile.goal} onChange={v=>change('goal',v)} options={[{value:'lose',label:'减脂'},{value:'maintain',label:'保持'},{value:'gain',label:'增肌'}]}/><Row title="特殊医疗、孕期或饮食需求"><Switch checked={profile.specialDiet} onChange={v=>change('specialDiet',v)}/></Row><Row title="以上限制和忌口已确认"><Switch checked={confirmed} onChange={setConfirmed}/></Row></Section><Button variant="primary" disabled={ai.busy||!confirmed} onClick={generate}>生成训练 + 一周饮食</Button></>}
    {ai.busy&&<Button onClick={ai.cancel}>取消请求</Button>}{error&&<p className="notice">{error}</p>}
    {proposal&&<><Section title="审核训练与饮食" footer={proposal.explanation}><Row title={proposal.program.nameZh} subtitle={proposal.program.days.map(d=>d.dayName+'：'+d.exerciseItems.map(item=>exerciseName(candidates.find(e=>e.id===item.exerciseId))).join('、')).join('\n')}/><Button onClick={()=>useUI.getState().openSheet(close=><ProgramReview initial={proposal.program} close={close} onConfirm={program=>setProposal({...proposal,program})}/>)}>编辑动作、组次、重量和休息</Button><Row title="营养目标" value={proposal.target.kcal+' kcal · 蛋白质 '+proposal.target.proteinG+' g'}/>
      {proposal.dates.map(date=><Section key={date} title={date} footer={nutritionLine(dailyTotals(proposal.snapshots,date))}>{proposal.meals.filter(m=>m.date===date).map(meal=><div className="card" key={date+meal.slot}><SelectRow title={{breakfast:'早餐',lunch:'午餐',dinner:'晚餐',snack:'加餐',pre:'训练前',post:'训练后'}[meal.slot]} value={meal.recipeId} options={recipes.map(r=>({value:r.id,label:r.nameZh}))} onChange={v=>{const meals=proposal.meals.map(m=>m===meal?{...m,recipeId:v}:m);setProposal({...proposal,meals,snapshots:validateMeals({meals},proposal.dates,recipes,foods,profile,proposal.target,uid,false)})}}/><Row title="份数"><NumberField value={meal.servings} onChange={v=>{if(v<.1||v>20)return;const meals=proposal.meals.map(m=>m===meal?{...m,servings:v}:m);setProposal({...proposal,meals,snapshots:validateMeals({meals},proposal.dates,recipes,foods,profile,proposal.target,uid,false)})}}/></Row></div>)}</Section>)}</Section><TextArea maxLength={2000} value={modification} placeholder="继续修改，例如：周五换成上肢，晚餐不想吃鸡肉" onChange={e=>setModification(e.target.value)}/><Button disabled={ai.busy||!modification.trim()} onClick={generate}>按这句话修改方案</Button><Button variant="primary" disabled={ai.busy||!!S.active||proposal.baseRevision!==S.xunlian.revision} onClick={apply}>确认并应用训练和饮食</Button></>}
  </div>
}
