import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { Section,Row,TextField,Button } from '../components/ui.jsx'
import { createKitchenAPI,kitchenRecipe,kitchenBase } from '../lib/howtocook-api.js'
import { useAIRequest } from '../lib/useAIRequest.js'
export default function Kitchen(){
  const S=useStore(s=>s.S),update=useStore(s=>s.update),nav=useNavigate(),[base,setBase]=useState(S.xunlian.kitchenApi||''),[query,setQuery]=useState(''),[list,setList]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),ai=useAIRequest()
  const run=fn=>ai.run(async signal=>{setError('');try{await fn(createKitchenAPI(base),signal)}catch(e){setError(e.message)}})
  return <div className="narrow"><h1>HowToCook 在线菜谱</h1><p className="sect-f">内置菜谱可离线使用。在线功能使用你配置的 HowToCook-API 兼容服务，只发送搜索词和菜谱 ID，不发送个人档案或密钥。</p><a href="https://github.com/LoCCai/HowToCook-API" target="_blank" rel="noreferrer">接口项目与部署说明</a><Section><TextField placeholder="https://你的菜谱服务地址" value={base} onChange={e=>setBase(e.target.value)}/><Button disabled={ai.busy} onClick={()=>run(async(api,signal)=>{await api.health(signal);update(s=>{s.xunlian.kitchenApi=kitchenBase(base)});setError('连接成功，地址已保存。')})}>测试并保存接口</Button><TextField value={query} placeholder="菜名或原料，例如鸡蛋、西红柿" onChange={e=>setQuery(e.target.value)}/><Button disabled={ai.busy||!query.trim()} onClick={()=>run(async(api,signal)=>{const data=await api.search(query,signal),items=Array.isArray(data)?data:data.recipes||data.items;if(!Array.isArray(items))throw new Error('接口列表格式不匹配。');setList(items.slice(0,30));setSelected(null)})}>搜索菜谱</Button></Section>{ai.busy&&<Button onClick={ai.cancel}>取消请求</Button>}{error&&<p className="notice">{error}</p>}<Section>{list.map(r=><Row key={r.id} title={r.title||r.name} accessory="chevron" onClick={()=>run(async(api,signal)=>setSelected(kitchenRecipe(await api.detail(r.id,signal),base)))}/>)}</Section>{selected&&<Section title={selected.nameZh} footer={selected.notes}><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit'}}>{selected.originalText||selected.steps.join('\n')}</pre><Button variant="primary" onClick={()=>{update(s=>{const old=s.xunlian.recipes.findIndex(r=>r.id===selected.id);if(old<0)s.xunlian.recipes.unshift(selected);else s.xunlian.recipes[old]={...selected,revision:(s.xunlian.recipes[old].revision||1)+1};s.xunlian.revision++});nav('/nutrition')}}>导入菜谱，继续审核原料</Button></Section>}<Button onClick={()=>nav('/nutrition')}>返回离线食谱</Button></div>
}
