import { requiredMealSlots } from '../lib/meal-slots.js'
import { requireAI, aiErrorMessage } from '../lib/ai-errors.js'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { t } from '../lib/i18n.js'
import { uid } from '../lib/format.js'
import foodSeeds from '../data/foods.json'
import seeds from '../data/recipes.json'
import { NUTRIENTS, recipeNutrition, mealSnapshot, scaleNutrition, dailyTotals, localDate, searchFood, shoppingList, monday, dateKeys, clone, planningContext, positive, validateTarget } from '../lib/nutrition.js'
import { mapEntity, normalizeName, stripTranscript } from '../lib/entity-mapping.js'
import { createDeepSeek } from '../lib/deepseek.js'
import { getCredential } from '../lib/credentials.js'
import { Section, Row, Button, TextField, TextArea, NumberField, Segmented, SelectRow, Switch } from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
import { confirmSheet } from '../sheets.jsx'
import { eligibleRecipes, recipeAllowed, validateMeals, mealDifference } from '../lib/planning-engine.js'
import { useAIRequest } from '../lib/useAIRequest.js'
import { balanceCoachMeals } from '../lib/meal-portions.js'
import { feasibleMenu } from '../lib/assistant-plan.js'
const foodCatalogs=new WeakMap(),recipeCatalogs=new WeakMap()
export const allFoods = S => {const custom=S.xunlian.foods;if(!custom?.length)return foodSeeds;let list=foodCatalogs.get(custom);if(!list){list=[...custom,...foodSeeds];foodCatalogs.set(custom,list)}return list}
export const allRecipes = S => {const custom=S.xunlian.recipes;if(!custom?.length)return seeds;let list=recipeCatalogs.get(custom);if(!list){list=[...custom,...seeds];recipeCatalogs.set(custom,list)}return list}
const names = {kcal:'Energy',proteinG:'Protein',carbsG:'Carbs',fatG:'Fat',fiberG:'Fiber',sodiumMg:'Sodium',potassiumMg:'Potassium',calciumMg:'Calcium',ironMg:'Iron'}
export const nutritionLine = n => `${n?.kcal == null ? '—' : Math.round(n.kcal)} kcal · ${t('Protein')} ${n?.proteinG == null ? '—' : Math.round(n.proteinG)} g`
export const mealSlots = ['breakfast','lunch','dinner','snack','pre','post']
export function NutritionValues({n}) {return <Section title={t('Nutrition')} footer={t('Missing values are unknown, not zero. Raw ingredient calculation; cooking losses are not measured.')}>
  {NUTRIENTS.map(k=><Row key={k} title={t(names[k])} value={n?.[k] == null ? t('Unknown') : `${Math.round(n[k]*10)/10} ${k==='kcal'?'kcal':k.endsWith('Mg')?'mg':'g'}`} />)}
</Section>}
function PickFood({close,onPick}) {
  const S=useStore(s=>s.S),foods=allFoods(S),[q,setQ]=useState('')
  return <><h2>{t('Choose ingredient')}</h2><TextField autoFocus placeholder={t('Search…')} value={q} onChange={e=>setQ(e.target.value)} />
  <Section>{foods.filter(f=>searchFood(f,q)).slice(0,40).map(f=><Row key={f.id} title={f.nameZh} subtitle={f.nameEn} value={f.foodType} onClick={()=>{onPick(f);close()}} />)}</Section></>
}
export function foodPicker(onPick){useUI.getState().openSheet(close=><PickFood close={close} onPick={onPick} />)}
function FoodEditor({initial,close}) {
  const [f,setF]=useState(initial||{id:uid(),nameZh:'',nameEn:'',foodType:'unspecified',nutritionPer100g:Object.fromEntries(NUTRIENTS.map(k=>[k,null])),source:'user-created',sourceRelease:'user-'+Date.now(),sourceUrl:'',verified:false}),[error,setError]=useState(''),update=useStore(s=>s.update)
  return <><h2>{t('New custom food')}</h2><TextField placeholder={t('Chinese name')} value={f.nameZh} onChange={e=>setF({...f,nameZh:e.target.value})}/><TextField placeholder={t('English name')} value={f.nameEn} onChange={e=>setF({...f,nameEn:e.target.value})}/><SelectRow title={t('Food state')} value={f.foodType} onChange={v=>setF({...f,foodType:v})} options={['raw','cooked','unspecified'].map(value=>({value,label:t(value)}))}/><p className="sect-f">{t('Enter values per 100 g from a label or measurement. Unfilled nutrients remain unknown.')}</p><Section>{NUTRIENTS.map(k=><Row key={k} title={t(names[k])+' ('+(k==='kcal'?'kcal':k.endsWith('Mg')?'mg':'g')+')'}><NumberField nullable value={f.nutritionPer100g[k]} onChange={v=>setF({...f,nutritionPer100g:{...f.nutritionPer100g,[k]:v}})}/></Row>)}</Section>{error&&<p className="notice">{error}</p>}<Button variant="primary" onClick={()=>{if(!f.nameZh.trim()||!Number.isFinite(f.nutritionPer100g.kcal)||f.nutritionPer100g.kcal<0||NUTRIENTS.some(k=>f.nutritionPer100g[k]!=null&&(!Number.isFinite(f.nutritionPer100g[k])||f.nutritionPer100g[k]<0||f.nutritionPer100g[k]>100000))){setError(t('Enter a name and valid nutrition values'));return}update(s=>{s.xunlian.foods=[...s.xunlian.foods.filter(v=>v.id!==f.id),{...f,nameZh:f.nameZh.trim(),nutritionBasis:'per100g edible portion',verified:false,revision:(f.revision||0)+1}];s.xunlian.revision++});close()}}>{t('Save')}</Button></>
}
function foodEditor(initial){useUI.getState().openSheet(close=><FoodEditor initial={initial} close={close}/>)}
function FoodDetail({food,close,date}) {
  const S=useStore(s=>s.S),[grams,setGrams]=useState(100), update=useStore(s=>s.update), toast=useUI(s=>s.toast)
  return <><h2>{food.nameZh}</h2><p className="muted">{food.nameEn}</p><p className="sect-f">{t('Per 100 g edible portion')} · {food.foodType} · {food.sourceRelease}</p><Row title={t('Amount (g)')}><NumberField value={grams} onChange={setGrams}/></Row>
    <NutritionValues n={positive(grams)?scaleNutrition(food.nutritionPer100g,grams/100):null}/>
    <Row title="原料价格（元 / 100克）" subtitle="按本条食材的生熟状态填写，不自动猜价格"><NumberField nullable value={S.xunlian.profile.foodPrices?.[food.id]} onChange={v=>{if(v!=null&&(!Number.isFinite(v)||v<0||v>10000))return;update(s=>{s.xunlian.profile.foodPrices={...(s.xunlian.profile.foodPrices||{})};if(v==null)delete s.xunlian.profile.foodPrices[food.id];else s.xunlian.profile.foodPrices[food.id]=v;s.xunlian.revision++})}}/></Row>
    <Button variant="primary" disabled={!positive(grams)} onClick={()=>{update(s=>s.xunlian.logs.push({id:uid(),date,slot:'snack',foodId:food.id,nameZh:food.nameZh,grams,nutritionSnapshot:scaleNutrition(food.nutritionPer100g,grams/100),nutritionSourceVersion:[food.sourceRelease],recordedAt:Date.now()}));toast(t('Intake recorded'));close()}}>{t('Record actual intake')}</Button>
    {food.source==='user-created'&&<Button onClick={()=>{close();foodEditor(food)}}>{t('Edit custom food')}</Button>}<p className="sect-f">{food.verified?t('Source database value'):t('User-provided nutrition values')}</p><a href={food.sourceUrl} target="_blank" rel="noreferrer">{t('Source')} · USDA FoodData Central</a></>
}
function RecipeDetail({recipe,close,date}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),toast=useUI(s=>s.toast),[servings,setServings]=useState(1)
  const foods=allFoods(S),result=positive(servings)?recipeNutrition(recipe,foods,servings):{nutrition:null,complete:false}, favorite=S.xunlian.favorites.includes(recipe.id)
  return <><h2>{recipe.nameZh}</h2><p className="muted">{recipe.nameEn}</p>{recipe.image&&<img className="recipe-cover" src={recipe.image} alt={recipe.nameZh}/>}
  <p className="sect-f">{recipe.source} · {recipe.license} · {t('Revision')} {recipe.revision||1}</p>
  {recipe.prepMinutes&&<p className="sect-f">备餐约 {recipe.prepMinutes} 分钟 · {recipe.prepTimeBasis||'菜谱标注'}</p>}
  {!result.complete&&<p className="notice">{t('Incomplete ingredient mapping or quantities. Nutrition is incomplete; review a copy before planning.')}</p>}
  {recipe.servingsBasis&&<p className="notice">{t('Source serving count needs review.')}</p>}
  <Row title={t('Servings')}><NumberField value={servings} onChange={setServings}/></Row><NutritionValues n={result.nutrition}/>
  <Section title={t('Ingredients')}>{recipe.ingredients.map((i,j)=>{const f=foods.find(f=>f.id===i.foodId);return <Row key={j} title={f?.nameZh||i.originalText} subtitle={i.originalText+(i.estimated?' · '+t('Estimated quantity'):'')} value={i.grams==null?'—':Math.round(i.grams*servings/recipe.servings)+' g'}/>})}</Section>
  <Section title={t('Steps')}><ol className="steps-list">{recipe.steps.map((step,i)=><li key={i}>{step}</li>)}</ol></Section>
  {recipe.notes&&<p className="sect-f">{recipe.notes}</p>}
  <div className="row" style={{flexWrap:'wrap',gap:8}}>
    <Button variant="primary" disabled={!result.complete||!Number.isFinite(result.nutrition?.kcal)} onClick={()=>{update(s=>s.xunlian.logs.push({...mealSnapshot(recipe,foods,servings,date,'lunch',uid()),recordedAt:Date.now()}));toast(t('Intake recorded'));close()}}>{t('Record actual intake')}</Button>
    {S.xunlian.recipes.some(r=>r.id===recipe.id)&&<Button onClick={()=>{close();recipeEditor(clone(recipe))}}>{t('Edit')}</Button>}<Button onClick={()=>{close();recipeEditor({...clone(recipe),id:uid(),source:'user-created',sourceRecipeId:recipe.id,originalSource:recipe.sourceUrl,sourceUrl:'',image:recipe.image})}}>{t('Edit a copy')}</Button>
    {S.xunlian.recipes.some(r=>r.id===recipe.id)&&<Button variant="danger" onClick={()=>confirmSheet({title:t('Delete recipe?'),message:t('Recorded meals keep their snapshots.'),danger:true,onConfirm:()=>{update(s=>{s.xunlian.recipes=s.xunlian.recipes.filter(r=>r.id!==recipe.id);s.xunlian.revision++});close()}})}>{t('Delete')}</Button>}<Button onClick={()=>update(s=>{s.xunlian.favorites=favorite?s.xunlian.favorites.filter(id=>id!==recipe.id):[...s.xunlian.favorites,recipe.id]})}>{t(favorite?'Unfavorite':'Favorite')}</Button>
  </div>{recipe.sourceUrl&&<a href={recipe.sourceUrl} target="_blank" rel="noreferrer">{t('Source')}</a>}</>
}
export function recipeDetail(recipe,date=localDate()){useUI.getState().openSheet(close=><RecipeDetail recipe={recipe} close={close} date={date}/>)}
function RecipeEditor({initial,close}) {
  const [r,setR]=useState(initial||{id:uid(),nameZh:'',nameEn:'',servings:1,ingredients:[],steps:[''],source:'user-created',license:'user content',revision:0}), [error,setError]=useState('')
  const S=useStore(s=>s.S),foods=allFoods(S),update=useStore(s=>s.update),toast=useUI(s=>s.toast)
  const change=(key,v)=>setR({...r,[key]:v}), ingredient=(index,patch)=>setR({...r,ingredients:r.ingredients.map((x,i)=>i===index?{...x,...patch}:x)})
  const result=positive(r.servings)?recipeNutrition(r,foods):{nutrition:null}
  return <><h2>{t('My recipe')}</h2><TextField placeholder={t('Chinese name')} value={r.nameZh} onChange={e=>change('nameZh',e.target.value)} /><TextField placeholder={t('English name')} value={r.nameEn} onChange={e=>change('nameEn',e.target.value)}/>
  <Row title={t('Recipe yield (servings)')}><NumberField value={r.servings} onChange={v=>change('servings',v)}/></Row>
  <Row title="备餐分钟（可选）"><NumberField nullable value={r.prepMinutes} onChange={v=>{if(v!=null&&(!Number.isFinite(v)||v<=0||v>600))return;setR({...r,prepMinutes:v,prepTimeBasis:'用户填写'})}}/></Row>
  <Section title={t('Ingredients')}>{r.ingredients.map((i,j)=>{const f=foods.find(f=>f.id===i.foodId);return <div key={j} className="card"><Row title={f?.nameZh||i.originalText||t('Unmapped')} subtitle={i.originalText} onClick={()=>foodPicker(f=>{ingredient(j,{foodId:f.id,mappingStatus:'user-resolved'});update(s=>{const term=i.foodName||i.originalText;if(term)s.xunlian.foodAliases[normalizeName(term)]=f.id})})}/><Row title={t('Amount (g)')}><NumberField nullable value={i.grams} onChange={grams=>ingredient(j,{grams,estimated:false})}/></Row><Row title={t('Estimated quantity')}><Switch checked={i.estimated} onChange={estimated=>ingredient(j,{estimated})}/></Row><Button variant="danger" onClick={()=>change('ingredients',r.ingredients.filter((_,n)=>n!==j))}>{t('Remove')}</Button></div>})}</Section>
  <Button icon="plus" onClick={()=>foodPicker(f=>change('ingredients',[...r.ingredients,{foodId:f.id,originalText:f.nameZh,grams:100,estimated:true,mappingStatus:'user-resolved'}]))}>{t('Add ingredient')}</Button>
  <TextField placeholder={t('Source / creator')} value={r.sourceName||''} onChange={e=>change('sourceName',e.target.value)}/><TextField placeholder={t('Source URL (optional)')} value={r.sourceUrl||''} onChange={e=>change('sourceUrl',e.target.value)}/><TextArea aria-label={t('Steps')} placeholder={t('One cooking step per line')} value={r.steps.join('\n')} onChange={e=>change('steps',e.target.value.split('\n'))}/>
  <NutritionValues n={result.nutrition}/>{error&&<p className="notice">{error}</p>}
  <Button variant="primary" onClick={()=>{try{if(!r.nameZh.trim()||!positive(r.servings,1000)||!r.ingredients.length||!r.steps.some(s=>s.trim()))throw new Error(t('Complete name, servings, ingredients and steps'));const next={...r,nameZh:r.nameZh.trim(),revision:(r.revision||0)+1,servingsBasis:'user-confirmed',createdAt:r.createdAt||Date.now(),updatedAt:Date.now()};update(s=>{s.xunlian.recipes=[...s.xunlian.recipes.filter(v=>v.id!==r.id),next];s.xunlian.revision++});toast(t('Recipe saved'));close()}catch(e){setError(e.message)}}}>{t('Save recipe')}</Button></>
}
export function recipeEditor(initial){useUI.getState().openSheet(close=><RecipeEditor initial={initial} close={close}/>)}
function RecipeImport({close}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update), [text,setText]=useState(''),{busy,run:runAI,cancel}=useAIRequest(),[error,setError]=useState(''),[draft,setDraft]=useState(null)
  const foods=allFoods(S)
  const parse=()=>runAI(async signal=>{setError('');try{if(!S.xunlian.ai.enabled)throw new Error(t('Enable AI in settings first'));const provider=createDeepSeek({credential:getCredential,model:S.xunlian.ai.model});const data=await provider.generateStructured('recipe',{text:stripTranscript(text),context:planningContext(S),foods:foods.filter(f=>f.translationSource==='manual').map(f=>({id:f.id,nameZh:f.nameZh,nameEn:f.nameEn}))},{signal});const r={...data,id:uid(),source:'creator-import',originalText:text,license:'user-provided source',revision:0,ingredients:data.ingredients.map(i=>{const m=mapEntity(i.foodName,foods,S.xunlian.foodAliases);return {...i,foodId:m.selectedExerciseId,mappingStatus:m.mappingStatus}})};setDraft(r);update(s=>{s.xunlian.drafts.unshift({kind:'recipe',data:r,at:Date.now()});s.xunlian.drafts=s.xunlian.drafts.slice(0,20)})}catch(e){setError(aiErrorMessage(e))}})
  return <><h2>{t('Import recipe')}</h2><p className="sect-f">{t('Only the text and necessary planning context are sent to DeepSeek after you press Analyze. Review before saving.')}</p><TextArea value={text} onChange={e=>setText(e.target.value)} placeholder={t('Paste text or subtitles')} maxLength={60000}/>
  <input aria-label={t('Import file')} type="file" accept=".txt,.md,.srt,.vtt" onChange={async e=>{const f=e.target.files[0];if(f?.size>300000){setError(t('File too large'));return}if(f)setText(await f.text())}}/>
  {error&&<p className="notice">{error}</p>}<Button variant="primary" disabled={busy||!text.trim()} onClick={parse}>{t(busy?'Analyzing…':'Analyze')}</Button>
  {busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}{draft&&<Section title={t('Review draft')}><Row title={draft.nameZh} subtitle={t('Resolve ingredients and quantities before saving')} onClick={()=>{close();recipeEditor(draft)}}/></Section>}</>
}
export default function Nutrition() {
  const [category,setCategory]=useState(''),[completeOnly,setCompleteOnly]=useState(false)
  const nav=useNavigate(),S=useStore(s=>s.S),update=useStore(s=>s.update),[tab,setTab]=useState('today'),[q,setQ]=useState(''),[date,setDate]=useState(localDate()),[shown,setShown]=useState(40),[onlyFavorites,setOnlyFavorites]=useState(false)
  const foods=allFoods(S),recipes=useMemo(()=>allRecipes(S),[S.xunlian.recipes]), actual=S.xunlian.logs.some(l=>l.date===date)?dailyTotals(S.xunlian.logs,date):{},planned=dailyTotals(S.xunlian.meals,date)
  const recipeCategory=r=>r.category||(r.id.startsWith('xl-combo-')?'应用组合':r.source==='user-created'?'我的菜谱':'来源精选'),categoryNames={aquatic:'水产',breakfast:'早餐',condiment:'调料',dessert:'甜点',drink:'饮品',meat_dish:'荤菜',vegetable_dish:'素菜',soup:'汤',staple:'主食'}
  const shownRecipes=recipes.filter(r=>(!category||recipeCategory(r)===category)&&(!completeOnly||recipeNutrition(r,foods).complete)&&(tab!=='mine'||S.xunlian.recipes.includes(r))&&(!onlyFavorites||S.xunlian.favorites.includes(r.id))&&[r.nameZh,r.nameEn,...(r.tags||[])].some(n=>n?.toLowerCase().includes(q.toLowerCase().trim())))
  return <div className="narrow"><div className="hdr"><button className="iconbtn" onClick={()=>nav('/home')}><Icon name="chevronLeft"/></button><div style={{flex:1}}><h1>{t('Nutrition')}</h1><div className="sub">{t('Local ingredients, recipes and actual intake')}</div></div><button className="iconbtn" aria-label={t('Weekly meals')} onClick={()=>nav('/nutrition/week')}><Icon name="calendar"/></button></div>
  <Segmented value={tab} onChange={v=>{setTab(v);setShown(40);setQ('')}} options={[['today','Today'],['recipes','Recipes'],['foods','Ingredients'],['mine','My recipes']].map(([value,label])=>({value,label:t(label)}))}/>
  {tab==='today'?<><Row title={t('Date')}><TextField type="date" value={date} onChange={e=>setDate(e.target.value)}/></Row><div className="tiles"><div className="tile"><div className="l">{t('Actual intake')}</div><div className="v">{actual.kcal==null?'—':Math.round(actual.kcal)} kcal</div></div><div className="tile"><div className="l">{t('Planned')}</div><div className="v">{planned.kcal==null?'—':Math.round(planned.kcal)} kcal</div></div><div className="tile"><div className="l">{t('Target')}</div><div className="v">{S.xunlian.target?.kcal||'—'}</div></div><div className="tile"><div className="l">{t('Protein')}</div><div className="v">{actual.proteinG==null?'—':Math.round(actual.proteinG)} / {S.xunlian.target?.proteinG||'—'} g</div></div></div>
  <Section><Row title={t('Weekly meals and shopping list')} accessory="chevron" onClick={()=>nav('/nutrition/week')}/><Row title={t('Joint weekly planning')} accessory="chevron" onClick={()=>nav('/joint')}/><Row title={t('Profile and nutrition targets')} accessory="chevron" onClick={()=>nav('/planning')}/><Row title={t('Weekly review')} accessory="chevron" onClick={()=>nav('/review')}/></Section>
  <Section title={t('Planned meals')} footer={t('Planned meals are never automatically counted as eaten.')}>{S.xunlian.meals.filter(m=>m.date===date).map(m=><Row key={m.id} title={m.nameZh} subtitle={`${t(m.slot)} · ${m.servings} ${t('Servings')} · ${nutritionLine(m.nutritionSnapshot)}`}><Button size="sm" disabled={S.xunlian.logs.some(l=>l.plannedMealId===m.id)} onClick={()=>update(s=>s.xunlian.logs.push({...clone(m),id:uid(),plannedMealId:m.id,recordedAt:Date.now()}))}>{t('Eaten')}</Button><Button size="sm" onClick={()=>useUI.getState().openSheet(close=><SwapMeal meal={m} close={close}/>)}>{t('Swap recipe')}</Button><Button size="sm" onClick={()=>mealLogEditor(m,date,false)}>{t('Edit portion')}</Button></Row>)}</Section>
  <Section title={t('Actual intake')}>{S.xunlian.logs.filter(m=>m.date===date).map(m=><Row key={m.id} title={m.nameZh} subtitle={nutritionLine(m.nutritionSnapshot)}><Button size="sm" onClick={()=>mealLogEditor(m,date,true)}>{t('Edit')}</Button><Button size="sm" variant="danger" onClick={()=>update(s=>{s.xunlian.logs=s.xunlian.logs.filter(l=>l.id!==m.id)})}>{t('Remove')}</Button></Row>)}</Section>
  <Button variant="primary" onClick={()=>foodPicker(f=>useUI.getState().openSheet(close=><FoodDetail food={f} close={close} date={date}/>))}>{t('Add food intake')}</Button><Button onClick={()=>setTab('recipes')}>{t('Choose recipe intake')}</Button><NutritionValues n={actual}/></>:<>
  <TextField placeholder={t('Search…')} value={q} onChange={e=>{setQ(e.target.value);setShown(40)}}/>
  {tab!=='foods'&&<><SelectRow title="菜谱分类" value={category} onChange={v=>{setCategory(v);setShown(40)}} options={[{value:'',label:'全部'},...[...new Set(recipes.map(recipeCategory))].sort().map(value=>({value,label:categoryNames[value]||value}))]}/><Row title="仅显示营养完整菜谱"><Switch checked={completeOnly} onChange={v=>{setCompleteOnly(v);setShown(40)}}/></Row></>}
  {tab!=='foods'&&<><div className="row" style={{gap:8,flexWrap:'wrap'}}><Button variant="tinted" icon="plus" onClick={()=>recipeEditor()}>{t('New recipe')}</Button><Button onClick={()=>nav('/kitchen')}>HowToCook 在线菜谱</Button><Button onClick={()=>useUI.getState().openSheet(close=><RecipeImport close={close}/>)}>{t('Import recipe')}</Button><Button onClick={()=>setOnlyFavorites(!onlyFavorites)}>{t(onlyFavorites?'All':'Favorites')}</Button></div><Section footer={t('Source recipes may require ingredient and serving review; incomplete nutrition is marked.')}>{shownRecipes.slice(0,shown).map(r=><Row key={r.id} title={r.nameZh} subtitle={r.nameEn||r.source} accessory="chevron" onClick={()=>recipeDetail(r,date)}/>)}</Section>{shownRecipes.length>shown&&<Button onClick={()=>setShown(shown+40)}>{t('Show more')}</Button>}</>}
  {tab==='foods'&&<><Button onClick={()=>foodEditor()}>{t('New custom food')}</Button><Section title={`${foods.length} ${t('Ingredients')}`}>{foods.filter(f=>searchFood(f,q)).slice(0,shown).map(f=><Row key={f.id} title={f.nameZh} subtitle={f.nameEn} accessory="chevron" onClick={()=>useUI.getState().openSheet(close=><FoodDetail food={f} close={close} date={date}/>)}/>)}</Section><Button onClick={()=>setShown(shown+40)}>{t('Show more')}</Button></>}
  </>}</div>
}
function PortionEdit({meal,date,isLog,close}) {
  const [quantity,setQuantity]=useState(meal.servings||meal.grams||100),update=useStore(s=>s.update)
  const old=meal.servings||meal.grams, factor=quantity/old
  return <><h2>{meal.nameZh}</h2><Row title={t(meal.grams?'Amount (g)':'Servings')}><NumberField value={quantity} onChange={setQuantity}/></Row><NutritionValues n={positive(factor)?scaleNutrition(meal.nutritionSnapshot,factor):null}/><Button variant="primary" disabled={!positive(quantity,meal.grams?100000:1000)} onClick={()=>{const next={...clone(meal),costSnapshotCny:meal.costSnapshotCny==null?null:meal.costSnapshotCny*factor,nutritionSnapshot:scaleNutrition(meal.nutritionSnapshot,factor),...(meal.grams?{grams:quantity}:{servings:quantity}),ingredientsSnapshot:meal.ingredientsSnapshot?.map(i=>({...i,grams:i.grams*factor}))};update(s=>{if(isLog)s.xunlian.logs=s.xunlian.logs.map(l=>l.id===meal.id?next:l);else s.xunlian.logs.push({...next,id:uid(),date,plannedMealId:meal.id,recordedAt:Date.now()})});close()}}>{t(isLog?'Save':'Record actual intake')}</Button></>
}
function mealLogEditor(meal,date,isLog){useUI.getState().openSheet(close=><PortionEdit meal={meal} date={date} isLog={isLog} close={close}/>)}
function SwapMeal({meal,close}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),ai=useAIRequest(),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[q,setQ]=useState('')
  const foods=allFoods(S),recipes=eligibleRecipes(allRecipes(S),foods,S.xunlian.profile).filter(r=>r.id!==meal.recipeId),baseRevision=S.xunlian.revision
  const pick=(r,servings=meal.servings||1)=>setSelected({...mealSnapshot(r,foods,servings,meal.date,meal.slot,meal.id),baseRevision})
  const generate=()=>ai.run(async signal=>{setError('');try{requireAI(S);const candidates=recipes.slice(0,80),validate=r=>{if(!candidates.some(c=>c.id===r.recipeId))throw new Error('Unknown recipe ID');const next=mealSnapshot(candidates.find(c=>c.id===r.recipeId),foods,r.servings,meal.date,meal.slot,meal.id);if(Math.abs(next.nutritionSnapshot.kcal-meal.nutritionSnapshot.kcal)>Math.max(100,meal.nutritionSnapshot.kcal*.3))throw new Error('Replacement energy must remain within 30% (minimum 100 kcal tolerance) of the original meal')};const r=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('swap',{context:planningContext(S),meal,dayTotals:dailyTotals(S.xunlian.meals,meal.date),recipes:candidates.map(r=>({id:r.id,name:r.nameZh,nutrition:recipeNutrition(r,foods).nutrition})),constraints:'Replacement energy within 30% (minimum 100 kcal tolerance) of original meal. Explain total impact.'},{signal,validate});pick(candidates.find(c=>c.id===r.recipeId),r.servings);setReason(r.explanation)}catch(e){setError(aiErrorMessage(e))}})
  const delta=selected?mealDifference(meal,selected):null
  return <><h2>{t('Swap recipe')}</h2><p>{meal.nameZh} · {nutritionLine(meal.nutritionSnapshot)}</p><p className="sect-f">{t('AI sends this meal, day totals, necessary profile and candidate recipes to DeepSeek. Review before replacing.')}</p><Button disabled={ai.busy} onClick={generate}>{t('AI recipe swap')}</Button>{ai.busy&&<Button onClick={ai.cancel}>{t('Cancel request')}</Button>}<TextField placeholder={t('Search…')} value={q} onChange={e=>setQ(e.target.value)}/><Section>{recipes.filter(r=>(r.nameZh+' '+r.nameEn).toLowerCase().includes(q.toLowerCase())).slice(0,40).map(r=><Row key={r.id} title={r.nameZh} subtitle={nutritionLine(recipeNutrition(r,foods,meal.servings||1).nutrition)} onClick={()=>{pick(r);setReason(t('Manual replacement'))}}/>)}</Section>{error&&<p className="notice">{error}</p>}{selected&&<Section title={t('Review proposal')} footer={reason}><Row title={selected.nameZh} subtitle={nutritionLine(selected.nutritionSnapshot)} value={`${delta.kcal>0?'+':''}${Math.round(delta.kcal)} kcal`}/><NutritionValues n={dailyTotals(S.xunlian.meals.map(m=>m.id===meal.id?selected:m),meal.date)}/><Button variant="primary" disabled={selected.baseRevision!==S.xunlian.revision} onClick={()=>{update(s=>{s.xunlian.snapshots.unshift({kind:'meal',meals:clone(s.xunlian.meals),at:Date.now()});s.xunlian.snapshots=s.xunlian.snapshots.slice(0,3);s.xunlian.meals=s.xunlian.meals.map(m=>m.id===meal.id?selected:m);s.xunlian.revision++});close()}}>{t('Apply after review')}</Button></Section>}</>
}
function PickMeal({date,slot,existing,close}) {
  const S=useStore(s=>s.S), update=useStore(s=>s.update), [q,setQ]=useState(''), [servings,setServings]=useState(existing?.servings||1)
  const foods=allFoods(S),recipes=eligibleRecipes(allRecipes(S),foods,S.xunlian.profile)
  return <><h2>{date} · {t(slot)}</h2><Row title={t('Servings')}><NumberField value={servings} onChange={setServings}/></Row><TextField placeholder={t('Search…')} value={q} onChange={e=>setQ(e.target.value)}/><Section>{recipes.filter(r=>(r.nameZh+' '+r.nameEn).toLowerCase().includes(q.toLowerCase())).slice(0,40).map(r=><Row key={r.id} title={r.nameZh} subtitle={nutritionLine(recipeNutrition(r,foods,positive(servings)?servings:1).nutrition)} onClick={()=>{if(!positive(servings,20))return;const meal=mealSnapshot(r,foods,servings,date,slot,existing?.id||uid());update(s=>{s.xunlian.meals=[...s.xunlian.meals.filter(m=>m.id!==existing?.id),meal];s.xunlian.revision++});close()}}/>)}</Section>{existing&&<Button variant="danger" onClick={()=>{update(s=>{s.xunlian.meals=s.xunlian.meals.filter(m=>m.id!==existing.id);s.xunlian.revision++});close()}}>{t('Remove planned meal')}</Button>}</>
}
export function WeeklyMeals() {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),nav=useNavigate(),[start,setStart]=useState(monday()),{busy,run:runAI,cancel}=useAIRequest(),[error,setError]=useState(''),[proposal,setProposal]=useState(null),[shopping,setShopping]=useState(false)
  const foods=allFoods(S),dates=dateKeys(start), meals=S.xunlian.meals.filter(m=>dates.includes(m.date)),list=shoppingList(meals)
  const generate=()=>runAI(async signal=>{setError('');try{
    requireAI(S,{target:true});const recipes=eligibleRecipes(allRecipes(S),foods,S.xunlian.profile).slice(0,80),context=planningContext(S),menu=feasibleMenu(recipes,foods,S.xunlian.target,{profile:S.xunlian.profile})
    if(!menu)throw new Error('当前菜谱无法满足营养目标，请补充符合忌口的完整菜谱。')
    let balanced
    const result=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('meal',{constraints:'Each date needs the supplied requiredSlots. Only supplied recipe IDs. Respect exclusions. Choose varied practical meals; local code calibrates servings using real nutrition. Use feasibleDayMenu if no suitable alternative.',context,dates,requiredSlots:requiredMealSlots(S.xunlian.profile),feasibleDayMenu:menu,recipes:recipes.map(r=>({id:r.id,name:r.nameZh,ingredients:r.ingredients.map(i=>foods.find(f=>f.id===i.foodId)?.nameZh),nutrition:recipeNutrition(r,foods).nutrition}))},{signal,validate:r=>{balanced=balanceCoachMeals(r,dates,recipes,foods,S.xunlian.profile,S.xunlian.target,menu,uid)}})
    setProposal({...result,meals:balanced.meals,explanation:[result.explanation,balanced.note].filter(Boolean).join(' '),snapshots:balanced.snapshots,dates,baseRevision:S.xunlian.revision})
  }catch(e){setError(e.code?aiErrorMessage(e):e.message)}})
  return <div className="narrow"><div className="hdr"><button className="iconbtn" onClick={()=>nav('/nutrition')}><Icon name="chevronLeft"/></button><h1>{t('Weekly meals')}</h1></div><Row title={t('Week start')}><TextField type="date" value={start} onChange={e=>{if(e.target.value){setStart(monday(e.target.value));setProposal(null)}}}/></Row>
  {S.xunlian.nutritionNeedsReview&&<Section title={t('Training plan changed')} footer={t('Review meals against your current training schedule.')}><Button onClick={generate}>{t('Check now')}</Button><Button onClick={()=>update(s=>{s.xunlian.nutritionNeedsReview=false})}>{t('Keep current meals')}</Button></Section>}
  <div className="row" style={{gap:8,flexWrap:'wrap'}}><Button variant="tinted" disabled={busy} onClick={generate}>{t(busy?'Analyzing…':'AI weekly meals')}</Button><Button onClick={()=>setShopping(!shopping)}>{t('Shopping list')}</Button><Button onClick={()=>nav('/planning')}>{t('Targets')}</Button></div>{busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}<p className="sect-f">{t('AI sends profile, training schedule and recipe candidates after you press Generate. Review daily totals before applying.')}</p>{error&&<p className="notice">{error}</p>}
  {proposal&&<Section title={t('Review proposal')} footer={proposal.explanation}>{dates.map(d=><Row key={d} title={d} subtitle={proposal.snapshots.filter(m=>m.date===d).map(m=>m.nameZh).join(' · ')} value={nutritionLine(dailyTotals(proposal.snapshots,d))}/>)}<Button variant="primary" disabled={proposal.baseRevision!==S.xunlian.revision} onClick={()=>{update(s=>{s.xunlian.snapshots.unshift({kind:'meal',meals:clone(s.xunlian.meals),at:Date.now()});s.xunlian.snapshots=s.xunlian.snapshots.slice(0,3);s.xunlian.meals=[...s.xunlian.meals.filter(m=>!dates.includes(m.date)),...proposal.snapshots];s.xunlian.nutritionNeedsReview=false;s.xunlian.revision++});setProposal(null)}}>{t('Apply after review')}</Button><Button onClick={()=>setProposal(null)}>{t('Reject')}</Button></Section>}
  {shopping?<Section title={t('Shopping list')}>{list.items.map(i=>{const f=foods.find(f=>f.id===i.foodId);return <Row key={i.foodId} title={f?.nameZh||i.foodId} subtitle={f?.nameEn} value={Math.round(i.grams)+' g'}/>})}</Section>:dates.map(date=>{const day=new Date(date+'T12:00:00').getDay(),rid=Object.hasOwn(S.dayPlan,date)?S.dayPlan[date]:S.week[day],routine=S.routines.find(r=>r.id===rid),total=dailyTotals(meals,date);return <Section key={date} title={date+' · '+(routine?.name||t('Rest day'))} footer={nutritionLine(total)+(S.xunlian.target?' · '+t('Target')+' '+S.xunlian.target.kcal+' kcal':'')}>{requiredMealSlots(S.xunlian.profile).map(slot=>{const meal=meals.find(m=>m.date===date&&m.slot===slot);return <Row key={slot} title={t(slot)} subtitle={meal?meal.nameZh+' · '+meal.servings+' '+t('Servings'):t('Choose recipe')} accessory="chevron" onClick={()=>useUI.getState().openSheet(close=><PickMeal date={date} slot={slot} existing={meal} close={close}/>)}/>})}{meals.filter(m=>m.date===date&&!requiredMealSlots(S.xunlian.profile).includes(m.slot)).map(m=><Row key={m.id} title={t(m.slot)} subtitle={m.nameZh} onClick={()=>useUI.getState().openSheet(close=><PickMeal date={date} slot={m.slot} existing={m} close={close}/>)}/>)}<Button size="sm" disabled={mealSlots.every(slot=>meals.some(m=>m.date===date&&m.slot===slot))} onClick={()=>{const slot=[...(routine?['pre','post']:[]),'snack',...mealSlots].find(slot=>!meals.some(m=>m.date===date&&m.slot===slot));if(slot)useUI.getState().openSheet(close=><PickMeal date={date} slot={slot} close={close}/>)}}>{t(routine?'Add training meal':'Add snack')}</Button></Section>})}</div>
}
