import { requireAI, aiErrorMessage } from '../lib/ai-errors.js'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { t } from '../lib/i18n.js'
import { targets, activityLevel, NUTRITION_SOURCES, planningContext, validateTarget,validatePlanningProfile, clone, dateKeys, monday, localDate } from '../lib/nutrition.js'
import { createDeepSeek, MODELS } from '../lib/deepseek.js'
import { getCredential, setCredential, clearCredential } from '../lib/credentials.js'
import { weeklyEvidence } from '../lib/programs.js'
import { Section, Row, TextField, TextArea, NumberField, SelectRow, Button, Switch } from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
import { useAIRequest } from '../lib/useAIRequest.js'
import { validateTrainingAdjustment, applyTrainingAdjustment } from '../lib/prescription.js'
import { ALLERGENS } from '../lib/planning-engine.js'
import { readClipboardText } from '../lib/clipboard.js'
export function DeepSeekSettings() {
  const [showKey,setShowKey]=useState(false)
  const S=useStore(s=>s.S),update=useStore(s=>s.update),[key,setKey]=useState(''),[exists,setExists]=useState(false),{busy,run:runAI,cancel}=useAIRequest(),[notice,setNotice]=useState('')
  useEffect(()=>{getCredential().then(v=>setExists(!!v)).catch(()=>setNotice(t('Secure storage unavailable')))},[])
  const run=fn=>runAI(async signal=>{setNotice('');try{await fn(signal)}catch(e){setNotice(t('AI error: {0}',t('AI '+(e.code||'credential'))))}})
  return <Section className="deepseek-settings" title="DeepSeek AI" footer={t('Optional online feature. API key is excluded from data and backups. Browser keys last only for this session.')}>
    <Row title={t('Enable AI')} subtitle={t('When used, necessary profile and input text are sent to DeepSeek.')}><Switch checked={S.xunlian.ai.enabled} onChange={v=>update(s=>{s.xunlian.ai.enabled=v})}/></Row>
    <SelectRow title={t('Model')} value={S.xunlian.ai.model} onChange={v=>update(s=>{s.xunlian.ai.model=v})} options={MODELS.map(value=>({value,label:value}))}/>
    <Row title={t('Credential')} value={t(exists?'Configured':'Not configured')}/><div className="credential-panel"><TextField type={showKey?'text':'password'} autoComplete="off" autoCapitalize="none" autoCorrect="off" spellCheck={false} placeholder={t('Enter API key')} value={key} onChange={e=>setKey(e.target.value)}/>
    <div className="credential-actions"><Button variant="tinted" disabled={busy} onClick={async()=>{try{const text=(await readClipboardText()).trim();if(!text||text.length>512||/\s/.test(text)){setNotice('剪贴板内容不是完整密钥，请重新复制。');return}setKey(text);setNotice('已粘贴，请保存密钥。')}catch(e){setNotice(e.message)}}}>粘贴密钥</Button><Button variant="tinted" onClick={()=>setShowKey(v=>!v)}>{showKey?'隐藏密钥':'显示密钥'}</Button>
    <Button disabled={busy||!key.trim()} onClick={()=>run(async()=>{const mode=await setCredential(key.trim());setKey('');setExists(true);setNotice(t(mode==='session'?'Saved for this session':'Saved in secure storage'))})}>{t('Save credential')}</Button><Button variant="tinted" disabled={busy} onClick={()=>run(async signal=>{await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).healthCheck(signal);setNotice(t('Connection successful'))})}>{t('Test connection')}</Button><Button className="credential-clear" disabled={busy} variant="danger" onClick={()=>run(async()=>{await clearCredential();setExists(false);setKey('');setNotice(t('Credential cleared'))})}>{t('Clear credential')}</Button></div>
    {busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}{notice&&<p className="sect-f" role="status">{notice}</p>}</div>
  </Section>
}
export default function Planning() {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),nav=useNavigate(),toast=useUI(s=>s.toast),[profile,setProfile]=useState(clone(S.xunlian.profile)),[target,setTarget]=useState(S.xunlian.target||{kcal:0,proteinG:0,fatG:0,carbsG:0,basis:'manual'}),[error,setError]=useState('')
  const change=(k,v)=>setProfile({...profile,[k]:v})
  const save=()=>{try{validateTarget(target);validatePlanningProfile(profile);update(s=>{s.xunlian.profile=profile;s.xunlian.target=target;s.xunlian.nutritionNeedsReview=!!s.xunlian.meals.length;s.xunlian.revision++});setTarget(clone(useStore.getState().S.xunlian.target));setProfile(clone(useStore.getState().S.xunlian.profile));toast(t('Profile saved'));setError('')}catch(e){setError(e.message)}}
  return <div className="narrow feature-page"><div className="hdr"><button className="iconbtn" onClick={()=>nav('/nutrition')}><Icon name="chevronLeft"/></button><h1>{t('Planning profile')}</h1></div>
  <Section title={t('Body and goals')} footer={t('Latest body weight is shared with training. Calculated targets are estimates and can be edited.')}>
  <SelectRow title={t('Goal')} value={profile.goal} onChange={v=>change('goal',v)} options={[['maintain','维持'],['lose','减脂'],['gain','增肌']].map(([value,label])=>({value,label:t(label)}))}/>
  <SelectRow title={t('Sex for BMR equation')} value={profile.sex||''} onChange={v=>change('sex',v)} options={[['','Not set'],['male','Male'],['female','Female']].map(([value,label])=>({value,label:t(label)}))}/>
  {[['age','Age'],['heightCm','Height (cm)'],['weightKg','Fallback weight (kg)'],['targetWeightKg','Target weight (kg)']].map(([key,label])=><Row key={key} title={t(label)}><NumberField nullable value={profile[key]} onChange={v=>change(key,v)}/></Row>)}
  <SelectRow title={t('Activity factor')} value={activityLevel(profile.activity)} onChange={v=>change('activity',v)} options={[{value:1.5,label:'低 · PAL 1.50'},{value:1.75,label:'中 · PAL 1.75'},{value:2,label:'高 · PAL 2.00'}]}/>
  <p className="sect-f">选择全天工作、生活与训练的综合活动水平。PAL已包含运动和食物热效应；每周健身几次不能直接等同于高活动量。</p><Row title={t('Special diet / pregnancy / medical constraints')}><Switch checked={profile.specialDiet} onChange={v=>change('specialDiet',v)}/></Row></Section>
  <Section title={t('Training and lifestyle')}>
  <SelectRow title="饮食方式" value={profile.dietStyle||'omnivore'} onChange={v=>change('dietStyle',v)} options={[{value:'omnivore',label:'不限'},{value:'vegetarian',label:'蛋奶素（不含肉和鱼）'},{value:'vegan',label:'纯素（不含动物食品）'}]}/>
  <Row title="单次备餐分钟上限" subtitle="可留空；菜谱时间为应用估算"><NumberField nullable value={profile.cookingMinutes} onChange={v=>change('cookingMinutes',v)}/></Row>
  <Row title="每日原料预算（元）" subtitle="可留空；准确校验需在食材详情填写价格"><NumberField nullable value={profile.dailyBudgetCny} onChange={v=>change('dailyBudgetCny',v)}/></Row>
  {ALLERGENS.map(a=><Row key={a} title={a+' · '+t('Exclude ingredient')}><Switch checked={(profile.excludedAllergens||[]).includes(a)} onChange={v=>change('excludedAllergens',v?[...(profile.excludedAllergens||[]),a]:(profile.excludedAllergens||[]).filter(x=>x!==a))}/></Row>)}
  {[['trainingExperience','Training experience'],['trainingGoal','Training goal'],['equipment','Available equipment'],['limitations','Injuries or limitations'],['cookingAvailability','Cooking availability and tools'],['allergies','Allergies / excluded foods'],['dislikedFoods','Disliked foods'],['preferences','Food preferences'],['budget','Budget'],['sleepSchedule','Sleep schedule'],['workSchedule','Work schedule']].map(([key,label])=><Row key={key} title={t(label)}><TextField value={profile[key]||''} onChange={e=>change(key,e.target.value)}/></Row>)}
  <Row title={t('Training time')}><TextField type="time" value={profile.trainingTime||'18:30'} onChange={e=>change('trainingTime',e.target.value)}/></Row>
  {[['trainingDays','Training days per week'],['trainingDuration','Session minutes'],['mealCount','Meals per day'],['repeatMeals','Acceptable repeated meals']].map(([key,label])=><Row key={key} title={t(label)}><NumberField nullable value={profile[key]} onChange={v=>change(key,v)}/></Row>)}</Section>
  <Section title={t('Nutrition target')} footer={target.basis==='manual'||!target.basis?'手动目标；修改档案后请核对适用性。':target.basis}>
  {[['kcal','Energy'],['proteinG','Protein'],['fatG','Fat'],['carbsG','Carbs']].map(([key,label])=><Row key={key} title={t(label)}><NumberField value={target[key]} onChange={v=>setTarget({kcal:target.kcal,proteinG:target.proteinG,fatG:target.fatG,carbsG:target.carbsG,[key]:v,basis:'manual'})}/></Row>)}
  {target.basis&&target.basis!=='manual'&&!target.nutritionPolicy&&<p className="notice">这是旧版估算目标。点击下方计算，可按已核对的官方指导更新。</p>}{target.bmr!=null&&<><Row title="基础代谢预测" value={target.bmr+' kcal/天'}/><Row title="全天消耗预测（含训练）" value={target.tdee+' kcal/天'}/><Row title="计划摄入 / 预测缺口" value={target.kcal+' / '+(target.deficitKcal??'—')+' kcal/天'}/>{target.notes?.map(note=><p key={note} className="sect-f">{note}</p>)}</>}<details><summary>官方依据与计算适用范围</summary><p className="sect-f">自动计算面向18–64岁成年人。基础代谢公式是预测，不是实测；按指南比例选取可编辑的均衡目标。食材生熟状态、称量和营养完整性决定餐食计算精度，不能据此声称所有微量营养素均达标。</p>{NUTRITION_SOURCES.map(source=><p key={source.url} className="sect-f"><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.pages}</p>)}</details><Button onClick={()=>{try{setError('');setTarget(targets(profile,planningContext({...S,xunlian:{...S.xunlian,profile}}).weightKg))}catch(e){setError(e.message)}}}>{t('Calculate suggested targets')}</Button></Section>
  {error&&<p className="notice">{error}</p>}<Button variant="primary" onClick={save}>{t('Save profile and targets')}</Button><Button onClick={()=>nav('/joint')}>{t('Joint weekly planning')}</Button><DeepSeekSettings/></div>
}
export function WeeklyReview() {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),nav=useNavigate(),{busy,run:runAI,cancel}=useAIRequest(),[error,setError]=useState(''),[result,setResult]=useState(null),[decisions,setDecisions]=useState({})
  const generate=()=>runAI(async signal=>{setError('');try{requireAI(S);const date=new Date();date.setDate(date.getDate()-6);const data=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('review',weeklyEvidence(S,dateKeys(localDate(date))),{signal,validate:data=>data.suggestions.forEach(a=>{if(['sets','prescription'].includes(a.action))validateTrainingAdjustment(S,a);if(a.action==='target')validateTarget(a.target)})});setResult({...data,baseRevision:S.xunlian.revision});setDecisions({});update(s=>{s.xunlian.proposals.unshift({...data,baseRevision:S.xunlian.revision,createdAt:Date.now()});s.xunlian.proposals=s.xunlian.proposals.slice(0,10)})}catch(e){setError(aiErrorMessage(e))}})
  const apply=()=>{try{if(result.baseRevision!==S.xunlian.revision)throw new Error(t('Plan changed; generate a new proposal'));const accepted=result.suggestions.filter((_,i)=>decisions[i]==='accept');if(!accepted.length)return
    if(S.active)throw new Error('训练中请先完成当前训练');const unique=new Set();accepted.forEach(a=>{if(a.action==='target')validateTarget(a.target);if(['sets','prescription'].includes(a.action)){const key=a.routineId+'|'+a.exerciseId;if(unique.has(key))throw new Error('同一动作请每次采纳一个微调建议');unique.add(key);validateTrainingAdjustment(S,a)}})
    update(s=>{s.xunlian.snapshots.unshift({kind:'joint',routines:clone(s.routines),week:clone(s.week),target:clone(s.xunlian.target),meals:clone(s.xunlian.meals),at:Date.now()});s.xunlian.snapshots=s.xunlian.snapshots.slice(0,3);accepted.forEach(a=>{if(a.action==='target')s.xunlian.target=a.target;if(['sets','prescription'].includes(a.action)){applyTrainingAdjustment(s,a);s.xunlian.nutritionNeedsReview=true}});s.xunlian.revision++});setResult(null)
  }catch(e){setError(e.message)}}
  const undo=()=>{const snap=S.xunlian.snapshots[0];if(!snap)return;update(s=>{if(snap.profile)s.xunlian.profile=clone(snap.profile);if(snap.routines)s.routines=clone(snap.routines);if(snap.week)s.week=clone(snap.week);if(snap.dayPlan)s.dayPlan=clone(snap.dayPlan);if(snap.programs)s.xunlian.programs=clone(snap.programs);if(snap.meals)s.xunlian.meals=clone(snap.meals);if(Object.hasOwn(snap,'target'))s.xunlian.target=clone(snap.target);s.xunlian.snapshots.shift();s.xunlian.revision++;s.xunlian.nutritionNeedsReview=true;return {skipBalance:true}})}
  return <div className="narrow feature-page"><div className="hdr"><button className="iconbtn" onClick={()=>nav('/nutrition')}><Icon name="chevronLeft"/></button><h1>{t('Weekly review')}</h1></div><p className="sect-f">{t('Review shares the last 7 days of training, food logs, recent weight and necessary profile. Suggestions never change plans automatically.')}</p><Button variant="primary" disabled={busy} onClick={generate}>{t(busy?'Analyzing…':'Generate weekly review')}</Button>{busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}{error&&<p className="notice">{error}</p>}
  {result&&<><Section title={t('Review proposal')} footer={result.summary}>{result.suggestions.map((a,i)=><div key={i} className="card"><h3>{a.title}</h3><p className="muted">{a.reason}</p><p className="sect-f">{t(a.domain)} · {a.action==='sets'?a.sets+' '+t('Sets'):a.action==='target'?a.target?.kcal+' kcal':a.action==='prescription'?['weight','reps','restSec'].filter(k=>a[k]!=null).map(k=>t(k)+' '+(S.routines.find(r=>r.id===a.routineId)?.ex.find(e=>e.id===a.exerciseId)?.[k]??'—')+' → '+a[k]+(k==='weight'?' '+S.unit:k==='restSec'?' s':'')).join(' · '):t('Suggestion only')}</p><Button variant={decisions[i]==='accept'?'primary':'plain'} onClick={()=>setDecisions({...decisions,[i]:'accept'})}>{t('Accept')}</Button><Button onClick={()=>setDecisions({...decisions,[i]:'reject'})}>{t('Reject')}</Button></div>)}</Section><Button variant="primary" disabled={result.baseRevision!==S.xunlian.revision||!!S.active} onClick={apply}>{t('Apply selected suggestions')}</Button></>}
  <Section title={t('Saved reviews')}>{S.xunlian.proposals.filter(p=>p.kind!=='joint').map((p,i)=><Row key={i} title={new Date(p.createdAt).toLocaleDateString()} subtitle={p.summary} onClick={()=>{setResult(p);setDecisions({})}}/>)}</Section><Button disabled={!S.xunlian.snapshots.length||!!S.active} onClick={undo}>{t('Undo latest plan change')}</Button></div>
}
