import { requireAI, aiErrorMessage } from '../lib/ai-errors.js'
import { useState } from 'react'
import chinaGuides from '../data/china-guides.json'
import { useNavigate } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { t } from '../lib/i18n.js'
import { uid } from '../lib/format.js'
import { allExercises, EXIDX } from '../lib/exercises.js'
import { builtInPrograms, guidelinePrograms, analyzeProgram, applyProgram, energyEstimate, validateProgram } from '../lib/programs.js'
import { mapEntity, normalizeName, stripTranscript } from '../lib/entity-mapping.js'
import { clone, planningContext, positive } from '../lib/nutrition.js'
import { createDeepSeek } from '../lib/deepseek.js'
import { getCredential } from '../lib/credentials.js'
import { confirmSheet, customExSheet } from '../sheets.jsx'
import { Thumb } from '../components/Media.jsx'
import { Section, Row, Button, TextField, TextArea, NumberField, SelectRow, Segmented } from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
import activityReference from '../data/activity-reference.json'
import { resolvePrescription } from '../lib/prescription.js'
import { parseProgramText } from '../lib/program-import.js'
import { useAIRequest } from '../lib/useAIRequest.js'
const weekdays=[1,2,3,4,5,6,0]
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
function ExercisePicker({original,candidates,onPick,close}) {
  const S=useStore(s=>s.S),[q,setQ]=useState(''),catalog=allExercises(S),filtered=q?catalog.filter(e=>[e.nameZh,e.nameEn,e.n,...(e.aliasesZh||[])].some(n=>n?.toLowerCase().includes(q.toLowerCase()))):candidates?.length?catalog.filter(e=>candidates.includes(e.id)):catalog
  return <><h2>{t('Resolve exercise')}</h2><p className="notice">{original} · {t('Confirm equipment, grip and angle; similar names can describe different exercises.')}</p><TextField placeholder={t('Search…')} value={q} onChange={e=>setQ(e.target.value)}/><Section>{filtered.slice(0,40).map(e=><Row key={e.id} title={e.nameZh||e.n} subtitle={(e.nameEn||e.n)+' · '+t(e.eq)+' · '+t(e.tg)} onClick={()=>{onPick(e);close()}}><Thumb ex={e}/></Row>)}</Section><Button onClick={()=>customExSheet(null,e=>{onPick(e);close()},original)}>{t('Create custom exercise')}</Button></>
}
export function ProgramReview({initial,close,onConfirm}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),toast=useUI(s=>s.toast),[p,setP]=useState(clone(initial)),[error,setError]=useState(''),[met,setMet]=useState(3.5),[metMax,setMetMax]=useState(6)
  const catalog=allExercises(S),analysis=analyzeProgram(p,catalog), unresolved=p.days.flatMap(d=>d.exerciseItems).filter(e=>!e.exerciseId||!['exact','high-confidence','user-resolved'].includes(e.mappingStatus))
  const edit=(day,index,patch)=>setP({...p,days:p.days.map((d,i)=>i===day?{...d,exerciseItems:d.exerciseItems.map((e,j)=>j===index?{...e,...patch}:e)}:d)})
  const resolve=(day,index,e)=>useUI.getState().openSheet(done=><ExercisePicker original={e.originalText} candidates={e.candidateExerciseIds} close={done} onPick={ex=>{edit(day,index,{exerciseId:ex.id,mappingStatus:'user-resolved'});update(s=>{s.xunlian.exerciseAliases[normalizeName(e.originalText)]=ex.id})}}/>)
  return <><h2>{t('Review program')}</h2><TextField value={p.nameZh} onChange={e=>setP({...p,nameZh:e.target.value})}/><p className="sect-f">{p.sourceName||t(p.sourceType)} · {p.days.length} {t('Training days')} · {analysis.estimatedWeeklyMinutes} {t('Minutes per week (estimated)')}</p>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">{t('Source')}</a>}
  {p.notes&&<p className="notice">{p.notes}</p>}{p.originalText&&<details><summary>{t('Source text')}</summary><pre style={{whiteSpace:'pre-wrap'}}>{p.originalText}</pre></details>}{unresolved.length>0&&<p className="notice">{t('{0} exercises need confirmation',unresolved.length)}</p>}
  <p className="sect-f">{t('Duration assumes 3 seconds per rep, default 90 seconds rest where unspecified, 5 minutes warm-up and 1 minute exercise transitions. Group rest estimates may overstate supersets.')}</p>
  <p className="sect-f">{t('Source parameters are prefilled. Accepted AI adjustments apply to future sessions; history stays unchanged.')}</p>
  {p.days.map((d,i)=><Section key={i} title={d.dayName} footer={`${analysis.days[i].estimatedDuration} ${t('Minutes (estimated)')} · ${t('Sets')} ${analysis.days[i].sets}${d.statedDuration?' · '+t('Source duration')+' '+d.statedDuration+' min':''}`}>
    <TextField aria-label={t('Training day name')} value={d.dayName} onChange={e=>setP({...p,days:p.days.map((x,j)=>i===j?{...x,dayName:e.target.value}:x)})}/><Button size="sm" variant="danger" onClick={()=>setP({...p,days:p.days.filter((_,j)=>j!==i)})}>{t('Remove training day')}</Button><SelectRow title={t('Weekday')} value={d.weekday} onChange={v=>setP({...p,days:p.days.map((x,j)=>i===j?{...x,weekday:v}:x)})} options={weekdays.map(value=>({value,label:t(dayNames[value])}))}/>
    {d.exerciseItems.map((e,j)=>{const ex=catalog.find(x=>x.id===e.exerciseId), resolved=resolvePrescription(S,e,ex,p);return <div key={j} className="card"><Row title={ex?.nameZh||e.originalText} subtitle={(ex?.nameEn||ex?.n||'')+' · '+t(e.mappingStatus)} accessory="chevron" onClick={()=>resolve(i,j,e)}><Thumb ex={ex||{}}/></Row><div className="prescription-grid">{[['sets','Sets'],['reps','Reps'],['repsMin','Min reps'],['repsMax','Max reps'],['weight','Weight'],['percent1RM','% 1RM'],['restSec','Rest seconds'],['durationSec','Duration seconds'],['rpe','RPE'],['rir','RIR']].map(([key,label])=><label key={key} className="small muted">{t(label)}<NumberField nullable value={e[key]} onChange={v=>edit(i,j,{[key]:v,estimatedFields:(e.estimatedFields||[]).filter(k=>k!==key)})}/></label>)}</div><SelectRow title={t('Source weight unit')} value={e.weightUnit||S.unit} onChange={v=>edit(i,j,{weightUnit:v})} options={['kg','lb'].map(value=>({value,label:value}))}/><p className="sect-f">{t('Session preset')}: {e.sets||'—'} {t('Sets')} × {resolved.reps||'—'} {t('Reps')} · {resolved.weight??'—'} {S.unit} · {t('Rest seconds')} {resolved.restSec} s · {t('Load basis '+resolved.prefillBasis.load)}{e.restSec==null?' · '+t('App default'):''}{e.percent1RM?' · '+e.percent1RM+'% 1RM':''}</p>{(resolved.prefillBasis.load==='pending'||e.baselineWeight!=null)&&<div className="notice"><p>{t('Enter your known working load and completed reps once. Reused for this exercise across days; never inferred from body weight.')}</p><label>{t('Baseline weight')} ({S.unit})<NumberField nullable value={e.baselineWeight} onChange={v=>setP({...p,days:p.days.map(day=>({...day,exerciseItems:day.exerciseItems.map(item=>item.exerciseId===e.exerciseId?{...item,baselineWeight:v,baselineUnit:S.unit}:item)}))})}/></label><label>{t('Completed baseline reps (1–12)')}<NumberField nullable value={e.baselineReps} onChange={v=>setP({...p,days:p.days.map(day=>({...day,exerciseItems:day.exerciseItems.map(item=>item.exerciseId===e.exerciseId?{...item,baselineReps:v}:item)}))})}/></label></div>}{!!e.estimatedFields?.length&&<p className="notice">{t('Inferred / app-arranged fields')}: {e.estimatedFields.map(k=>t(k)).join(', ')}</p>}{e.notes&&<p className="sect-f">{e.notes}</p>}<TextField placeholder={t('Superset / circuit group')} value={e.supersetGroup||e.circuitGroup||''} onChange={ev=>edit(i,j,{supersetGroup:ev.target.value})}/><Button variant="danger" size="sm" onClick={()=>setP({...p,days:p.days.map((x,k)=>k===i?{...x,exerciseItems:x.exerciseItems.filter((_,n)=>n!==j)}:x)})}>{t('Exclude this exercise')}</Button></div>})}
    <Button icon="plus" onClick={()=>useUI.getState().openSheet(done=><ExercisePicker original="" close={done} onPick={ex=>setP({...p,days:p.days.map((x,k)=>k===i?{...x,exerciseItems:[...x.exerciseItems,{exerciseId:ex.id,originalText:ex.nameZh||ex.n,mappingStatus:'user-resolved',sets:3,reps:10,restSec:90,estimatedFields:['sets','reps','restSec']}]}:x)})}/>)}>{t('Add exercise')}</Button>
  </Section>)}
  <Button disabled={p.days.length>=7} icon="plus" onClick={()=>{const weekday=weekdays.find(v=>!p.days.some(d=>d.weekday===v));setP({...p,days:[...p.days,{weekday,dayName:t(dayNames[weekday]),exerciseItems:[]}]})}}>{t('Add training day')}</Button><Section title={t('Primary muscle sets per week')} footer={t('Primary muscle counts only; secondary work and effective sets require interpretation.')}>{Object.entries(analysis.muscles).map(([muscle,n])=><Row key={muscle} title={t(muscle)} value={n}/>)}</Section>
  <Section title={t('Estimated energy expenditure')} footer={t('MET is an estimate. Gross energy includes resting energy and is not automatically added to nutrition targets.')}><SelectRow title={t('Reference activity')} value={p.activityCode||''} onChange={v=>{const a=activityReference.activities.find(a=>a.code===v);setP({...p,activityCode:v});if(a){setMet(a.met);setMetMax(a.met)}}} options={[{value:'',label:t('Manual MET range')},...activityReference.activities.map(a=>({value:a.code,label:a.nameZh+' · '+a.met+' MET'}))]}/><p className="sect-f"><a href={activityReference.sourceUrl} target="_blank" rel="noreferrer">2024 Adult Compendium of Physical Activities</a></p><Row title={t('MET min')}><NumberField value={met} onChange={setMet}/></Row><Row title={t('MET max')}><NumberField value={metMax} onChange={setMetMax}/></Row>{positive(planningContext(S).weightKg)&&positive(met)&&metMax>=met&&analysis.days.map((d,i)=>{const est=energyEstimate(planningContext(S).weightKg,d.estimatedDuration,met,metMax);return <Row key={i} title={d.dayName} subtitle={t('Low confidence; estimated duration')} value={`${est.kcalMin}–${est.kcalMax} kcal`}/>})}</Section>
  {error&&<p className="notice">{error}</p>}<div className="row" style={{gap:8,flexWrap:'wrap'}}><Button variant="primary" disabled={!!unresolved.length||!!S.active} onClick={()=>{try{if(onConfirm){validateProgram(p,catalog);onConfirm(p);close()}else{update(s=>applyProgram(s,p,allExercises(s),uid));toast(t('Program applied'));close()}}catch(e){setError(t('Cannot apply: {0}',e.message))}}}>{onConfirm?'保存到待审核方案':t('Apply to weekly training')}</Button><p className="sect-f">{t('Replaces the weekly schedule and clears future date overrides; previous routines remain in the library.')}</p><Button onClick={()=>{update(s=>{s.xunlian.drafts.unshift({kind:'program',data:p,at:Date.now()});s.xunlian.drafts=s.xunlian.drafts.slice(0,20)});toast(t('Draft saved'));close()}}>{t('Save draft')}</Button></div></>
}
function ImportProgram({close,generate=false}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),[text,setText]=useState(''),[sourceName,setSourceName]=useState(''),[sourceUrl,setSourceUrl]=useState(''),{busy,run:runAI,cancel}=useAIRequest(),[error,setError]=useState(''),[draft,setDraft]=useState(null)
  const readSource=()=>{setError('');try{const result=parseProgramText(stripTranscript(text),allExercises(S),S.xunlian.exerciseAliases);setDraft({...result,id:uid(),sourceType:'creator-import',sourceName:sourceName||'用户导入原文',sourceUrl,originalText:text,importedAt:Date.now(),baseRevision:S.xunlian.revision})}catch(e){setError(e.message)}}
  const analyze=()=>runAI(async signal=>{setError('');try{requireAI(S);const catalog=allExercises(S);const result=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('program',{task:generate?'Generate an executable plan using only supplied exercises':'Parse source text; do not invent source parameters',text:stripTranscript(text),context:planningContext(S),exercises:catalog.filter(e=>e.translationSource==='manual'||e.custom).slice(0,120).map(e=>({id:e.id,nameZh:e.nameZh,nameEn:e.nameEn||e.n,equipment:e.eq}))},{signal});const p={...result,id:uid(),sourceType:generate?'ai-generated':'creator-import',sourceName,sourceUrl,originalText:text,importedAt:Date.now(),baseRevision:S.xunlian.revision,days:result.days.map(d=>({...d,exerciseItems:d.exerciseItems.map(e=>{const mapping=mapEntity(e.originalText,catalog,S.xunlian.exerciseAliases);return {...e,...mapping,exerciseId:mapping.selectedExerciseId}})}))};setDraft(p);update(s=>{s.xunlian.drafts.unshift({kind:'program',data:p,at:Date.now()});s.xunlian.drafts=s.xunlian.drafts.slice(0,20)})}catch(e){setError(aiErrorMessage(e))}})
  return <><h2>{t(generate?'AI training plan':'Import training program')}</h2><TextField placeholder={t('Source / creator')} value={sourceName} onChange={e=>setSourceName(e.target.value)}/><TextField placeholder={t('Source URL (optional)')} value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/><TextArea maxLength={60000} placeholder={t(generate?'Describe your training needs':'Paste text or subtitles')} value={text} onChange={e=>setText(e.target.value)}/><input type="file" aria-label={t('Import file')} accept=".txt,.md,.srt,.vtt" onChange={async e=>{const f=e.target.files[0];if(f?.size>300000){setError(t('File too large'));return}if(f)setText(await f.text())}}/><p className="sect-f">{t('Only the text and necessary planning context are sent to DeepSeek after you press Analyze. Review before saving.')}</p>{!generate&&<><p className="sect-f">{t('Explicit text format: Monday / barbell bench press 40kg 3×8 rest 120s. Local parsing preserves written numbers; AI handles free-form text after review.')}</p><Button variant="primary" disabled={busy||!text.trim()} onClick={readSource}>{t('Read source parameters offline')}</Button></>}{error&&<p className="notice">{error}</p>}<Button disabled={busy||!text.trim()} onClick={analyze}>{t(busy?'Analyzing…':'AI Analyze')}</Button>{busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}{draft&&<Button onClick={()=>{close();useUI.getState().openSheet(done=><ProgramReview initial={draft} close={done}/>)}}>{t('Review program')}</Button>}</>
}
export default function Programs() {
  const S=useStore(s=>s.S),nav=useNavigate(),[tab,setTab]=useState('templates'),templates=[...guidelinePrograms(allExercises(S)),...builtInPrograms(allExercises(S))],show=p=>useUI.getState().openSheet(close=><ProgramReview initial={p} close={close}/>)
  const create=()=>{const days=S.routines.slice(0,7).filter(r=>r.ex.length).map((r,i)=>({weekday:weekdays[i],dayName:r.name,exerciseItems:r.ex.map(e=>({exerciseId:e.id,originalText:EXIDX[e.id]?.nameEn||EXIDX[e.id]?.n||e.id,mappingStatus:EXIDX[e.id]?'exact':'unmapped',sets:e.sets,reps:e.reps,weight:e.weight,durationSec:e.sec,restSec:S.restSec,supersetGroup:e.sg,estimatedFields:[]}))}));show({id:uid(),nameZh:t('My training program'),nameEn:'',sourceType:'user-created',sourceName:'',progression:'off',days:days.length?days:[{weekday:1,dayName:t('Monday'),exerciseItems:[]}]})}
  return <div className="narrow"><div className="hdr"><button className="iconbtn" onClick={()=>nav('/plan')}><Icon name="chevronLeft"/></button><div><h1>{t('Training programs')}</h1><div className="sub">{t('Templates, imports and executable plans')}</div></div></div><Segmented value={tab} onChange={setTab} options={[['templates','Templates'],['saved','My programs'],['drafts','Drafts']].map(([value,label])=>({value,label:t(label)}))}/><div className="row" style={{gap:8,flexWrap:'wrap',marginTop:12}}><Button variant="tinted" onClick={create}>{t('Create program')}</Button><Button onClick={()=>useUI.getState().openSheet(close=><ImportProgram close={close}/>)}>{t('Import')}</Button><Button onClick={()=>useUI.getState().openSheet(close=><ImportProgram close={close} generate/>)}>{t('AI training plan')}</Button></div><Section title={t(tab==='templates'?'Built-in templates':tab==='saved'?'My programs':'Drafts')} footer={t('Common split templates; they are not official programs from a guideline organization. Review before applying.')}>
  {(tab==='templates'?templates:tab==='saved'?S.xunlian.programs:S.xunlian.drafts.filter(d=>d.kind==='program').map(d=>d.data)).map((p,i)=><Row key={p.id+'-'+i} title={p.nameZh} subtitle={p.nameEn+' · '+t(p.sourceType)} value={p.days.length+' '+t('Training days')} accessory="chevron" onClick={()=>show(p)}/>)}</Section><Section title="中国健身与体重管理参考" footer="指南原则和应用编排分别标注；军体资料不作为普通新手的默认考核标准。">{chinaGuides.map(g=><div className="card" key={g.id}><h3>{g.title}</h3><p className="sect-f">{g.publisher} · {g.year}</p><p>{g.summary}</p><p className="sect-f">{g.application}</p><a href={g.url} target="_blank" rel="noreferrer">原始来源</a></div>)}</Section><Button onClick={()=>nav('/assistant')}>AI 对话生成训练与饮食</Button><Button onClick={()=>nav('/review')}>{t('Weekly review')}</Button></div>
}
