import {validateRecovery} from '../lib/training-recovery.js'
import { requireAI, aiErrorMessage } from '../lib/ai-errors.js'
import { useMemo, useState } from 'react'
import CreatorPrograms from '../components/CreatorPrograms.jsx'
import {creatorMappedProgram} from '../lib/creator-programs.js'
import chinaGuides from '../data/china-guides.json'
import { knowledgePrograms } from '../lib/knowledge-programs.js'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useStore } from '../store/useStore.js'
import { useUI } from '../store/useUI.js'
import { t } from '../lib/i18n.js'
import { uid } from '../lib/format.js'
import { allExercises, EXIDX } from '../lib/exercises.js'
import { analyzeProgram, applyProgram, energyEstimate, validateProgram, prefillProgram } from '../lib/programs.js'
import { mapEntity, normalizeName, stripTranscript } from '../lib/entity-mapping.js'
import { clone, planningContext, positive } from '../lib/nutrition.js'
import { createDeepSeek } from '../lib/deepseek.js'
import { getCredential } from '../lib/credentials.js'
import { confirmSheet, customExSheet } from '../sheets.jsx'
import { Thumb } from '../components/Media.jsx'
import { Section, Row, Button, TextField, TextArea, NumberField, SelectRow, Segmented } from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
import activityReference from '../data/activity-reference.json'
import { resolvePrescription } from '../lib/prescription.js'
import { parseProgramText } from '../lib/program-import.js'
import { useAIRequest } from '../lib/useAIRequest.js'
import { matchesProgram, goalLabels, intensityLabels, bodyLabels } from '../lib/program-filters.js'
const weekdays=[1,2,3,4,5,6,0]
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
function ExercisePicker({original,candidates,onPick,close}) {
  const S=useStore(s=>s.S),[q,setQ]=useState(''),catalog=allExercises(S),filtered=q?catalog.filter(e=>[e.nameZh,e.nameEn,e.n,...(e.aliasesZh||[])].some(n=>n?.toLowerCase().includes(q.toLowerCase()))):candidates?.length?catalog.filter(e=>candidates.includes(e.id)):catalog
  return <><h2>{t('Resolve exercise')}</h2><p className="notice">{original} · {t('Confirm equipment, grip and angle; similar names can describe different exercises.')}</p><TextField placeholder={t('Search…')} value={q} onChange={e=>setQ(e.target.value)}/><Section>{filtered.slice(0,40).map(e=><Row key={e.id} title={e.nameZh||e.n} subtitle={(e.nameEn||e.n)+' · '+t(e.eq)+' · '+t(e.tg)} onClick={()=>{onPick(e);close()}}><Thumb ex={e}/></Row>)}</Section><Button onClick={()=>customExSheet(null,e=>{onPick(e);close()},original)}>{t('Create custom exercise')}</Button></>
}
export function ProgramReview({initial,close,onConfirm}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),toast=useUI(s=>s.toast),[p,setP]=useState(()=>prefillProgram(S,initial,allExercises(S))),[error,setError]=useState(''),[met,setMet]=useState(3.5),[metMax,setMetMax]=useState(6)
  const catalog=allExercises(S),analysis=analyzeProgram(p,catalog), unresolved=p.days.flatMap(d=>d.exerciseItems).filter(e=>!e.exerciseId||!['exact','high-confidence','user-resolved'].includes(e.mappingStatus))
  let creatorWarning='';if(p.sourceType==='creator-derived')try{validateRecovery(p,catalog,planningContext(S))}catch(e){creatorWarning=e.message}
  const edit=(day,index,patch)=>setP({...p,days:p.days.map((d,i)=>i===day?{...d,exerciseItems:d.exerciseItems.map((e,j)=>j===index?{...e,...patch}:e)}:d)})
  const resolve=(day,index,e)=>useUI.getState().openSheet(done=><ExercisePicker original={e.originalText} candidates={e.candidateExerciseIds} close={done} onPick={ex=>{edit(day,index,{exerciseId:ex.id,mappingStatus:'user-resolved'});update(s=>{s.xunlian.exerciseAliases[normalizeName(e.originalText)]=ex.id})}}/>)
  return <><h2>{t('Review program')}</h2><TextField value={p.nameZh} onChange={e=>setP({...p,nameZh:e.target.value})}/><p className="sect-f">{p.sourceName||t(p.sourceType)} · {p.days.length} {t('Training days')} · {analysis.estimatedWeeklyMinutes} {t('Minutes per week (estimated)')}</p>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">{t('Source')}</a>}
  {p.notes&&<p className="notice">{p.notes}</p>}{p.originalText&&<details><summary>{t('Source text')}</summary><pre style={{whiteSpace:'pre-wrap'}}>{p.originalText}</pre></details>}{unresolved.length>0&&<p className="notice">{t('{0} exercises need confirmation',unresolved.length)}</p>}
  <p className="sect-f">{t('Duration assumes 3 seconds per rep, default 90 seconds rest where unspecified, 5 minutes warm-up and 1 minute exercise transitions. Group rest estimates may overstate supersets.')}</p>
  <p className="sect-f">{t('Source parameters are prefilled. Accepted AI adjustments apply to future sessions; history stays unchanged.')}</p>
  {p.days.map((d,i)=><Section key={i} title={d.dayName} footer={`${analysis.days[i].estimatedDuration} ${t('Minutes (estimated)')} · ${t('Sets')} ${analysis.days[i].sets}${d.statedDuration?' · '+t('Source duration')+' '+d.statedDuration+' min':''}`}>
    <TextField aria-label={t('Training day name')} value={d.dayName} onChange={e=>setP({...p,days:p.days.map((x,j)=>i===j?{...x,dayName:e.target.value}:x)})}/><Button size="sm" variant="danger" onClick={()=>setP({...p,days:p.days.filter((_,j)=>j!==i)})}>{t('Remove training day')}</Button><SelectRow title={t('Weekday')} value={d.weekday} onChange={v=>setP({...p,days:p.days.map((x,j)=>i===j?{...x,weekday:v}:x)})} options={weekdays.map(value=>({value,label:t(dayNames[value])}))}/>
    {d.exerciseItems.map((e,j)=>{const ex=catalog.find(x=>x.id===e.exerciseId), resolved=resolvePrescription(S,e,ex,p);return <div key={j} className="card"><Row title={ex?.nameZh||e.originalText} subtitle={(ex?.nameEn||ex?.n||'')+' · '+t(e.mappingStatus)} accessory="chevron" onClick={()=>resolve(i,j,e)}><Thumb ex={ex||{}}/></Row><div className="prescription-grid">{[['sets','Sets'],['reps','Reps'],['repsMin','Min reps'],['repsMax','Max reps'],['weight','Weight'],['percent1RM','% 1RM'],['restSec','Rest seconds'],['durationSec','Duration seconds'],['rpe','RPE'],['rir','RIR']].map(([key,label])=><label key={key} className="small muted">{t(label)}<NumberField nullable value={e[key]} onChange={v=>edit(i,j,{[key]:v,estimatedFields:(e.estimatedFields||[]).filter(k=>k!==key)})}/></label>)}</div><SelectRow title={t('Source weight unit')} value={e.weightUnit||S.unit} onChange={v=>edit(i,j,{weightUnit:v})} options={['kg','lb'].map(value=>({value,label:value}))}/><p className="sect-f">{t('Session preset')}: {e.sets||'—'} {t('Sets')} × {resolved.reps||'—'} {t('Reps')} · {resolved.weight??'—'} {S.unit} · {t('Rest seconds')} {resolved.restSec} s · {t('Load basis '+resolved.prefillBasis.load)}{e.restSec==null?' · '+t('App default'):''}{e.percent1RM?' · '+e.percent1RM+'% 1RM':''}</p>{(resolved.prefillBasis.load==='pending'||e.baselineWeight!=null)&&<div className="notice"><p>{t('Enter your known working load and completed reps once. Reused for this exercise across days; never inferred from body weight.')}</p><label>{t('Baseline weight')} ({S.unit})<NumberField nullable value={e.baselineWeight} onChange={v=>setP({...p,days:p.days.map(day=>({...day,exerciseItems:day.exerciseItems.map(item=>item.exerciseId===e.exerciseId?{...item,baselineWeight:v,baselineUnit:S.unit}:item)}))})}/></label><label>{t('Completed baseline reps (1–12)')}<NumberField nullable value={e.baselineReps} onChange={v=>setP({...p,days:p.days.map(day=>({...day,exerciseItems:day.exerciseItems.map(item=>item.exerciseId===e.exerciseId?{...item,baselineReps:v}:item)}))})}/></label></div>}{!!e.estimatedFields?.length&&<p className="notice">{t('Inferred / app-arranged fields')}: {e.estimatedFields.map(k=>t(k)).join(', ')}</p>}{e.notes&&<p className="sect-f">{e.notes}</p>}<TextField placeholder={t('Superset / circuit group')} value={e.supersetGroup||e.circuitGroup||''} onChange={ev=>edit(i,j,{supersetGroup:ev.target.value})}/><Button variant="danger" size="sm" onClick={()=>setP({...p,days:p.days.map((x,k)=>k===i?{...x,exerciseItems:x.exerciseItems.filter((_,n)=>n!==j)}:x)})}>{t('Exclude this exercise')}</Button></div>})}
    <Button icon="plus" onClick={()=>useUI.getState().openSheet(done=><ExercisePicker original="" close={done} onPick={ex=>setP({...p,days:p.days.map((x,k)=>k===i?{...x,exerciseItems:[...x.exerciseItems,{exerciseId:ex.id,originalText:ex.nameZh||ex.n,mappingStatus:'user-resolved',sets:3,reps:10,restSec:90,estimatedFields:['sets','reps','restSec']}]}:x)})}/>)}>{t('Add exercise')}</Button>
  </Section>)}
  <Button disabled={p.days.length>=7} icon="plus" onClick={()=>{const weekday=weekdays.find(v=>!p.days.some(d=>d.weekday===v));setP({...p,days:[...p.days,{weekday,dayName:t(dayNames[weekday]),exerciseItems:[]}]})}}>{t('Add training day')}</Button><Section title={t('Primary muscle sets per week')} footer={t('Primary muscle counts only; secondary work and effective sets require interpretation.')}>{Object.entries(analysis.muscles).map(([muscle,n])=><Row key={muscle} title={t(muscle)} value={n}/>)}</Section>
  <Section title={t('Estimated energy expenditure')} footer={t('MET is an estimate. Gross energy includes resting energy and is not automatically added to nutrition targets.')}><SelectRow title={t('Reference activity')} value={p.activityCode||''} onChange={v=>{const a=activityReference.activities.find(a=>a.code===v);setP({...p,activityCode:v});if(a){setMet(a.met);setMetMax(a.met)}}} options={[{value:'',label:t('Manual MET range')},...activityReference.activities.map(a=>({value:a.code,label:a.nameZh+' · '+a.met+' MET'}))]}/><p className="sect-f"><a href={activityReference.sourceUrl} target="_blank" rel="noreferrer">2024 Adult Compendium of Physical Activities</a></p><Row title={t('MET min')}><NumberField value={met} onChange={setMet}/></Row><Row title={t('MET max')}><NumberField value={metMax} onChange={setMetMax}/></Row>{positive(planningContext(S).weightKg)&&positive(met)&&metMax>=met&&analysis.days.map((d,i)=>{const est=energyEstimate(planningContext(S).weightKg,d.estimatedDuration,met,metMax);return <Row key={i} title={d.dayName} subtitle={t('Low confidence; estimated duration')} value={`${est.kcalMin}–${est.kcalMax} kcal`}/>})}</Section>
  {creatorWarning&&<p className="notice">{creatorWarning} 原表仍可查看和编辑；请返回该方案选择生成个人训练与饮食，按档案调整后使用。</p>}{error&&<p className="notice">{error}</p>}<div className="row" style={{gap:8,flexWrap:'wrap'}}><Button variant="primary" disabled={!!unresolved.length||!!S.active||!!creatorWarning} onClick={()=>{try{if(onConfirm){validateProgram(p,catalog);onConfirm(p);close()}else{update(s=>applyProgram(s,p,allExercises(s),uid));toast(t('Program applied'));close()}}catch(e){setError(t('Cannot apply: {0}',e.message))}}}>{onConfirm?'保存到待审核方案':t('Apply to weekly training')}</Button><p className="sect-f">{t('Replaces the weekly schedule and clears future date overrides; previous routines remain in the library.')}</p><Button onClick={()=>{update(s=>{s.xunlian.drafts.unshift({kind:'program',data:p,at:Date.now()});s.xunlian.drafts=s.xunlian.drafts.slice(0,20)});toast(t('Draft saved'));close()}}>{t('Save draft')}</Button></div></>
}
function ImportProgram({close,generate=false,initialSource=null}) {
  const S=useStore(s=>s.S),update=useStore(s=>s.update),[text,setText]=useState(''),[sourceName,setSourceName]=useState(initialSource?initialSource.creator+' · '+initialSource.name:''),[sourceUrl,setSourceUrl]=useState(initialSource?.url||''),{busy,run:runAI,cancel}=useAIRequest(),[error,setError]=useState(''),[draft,setDraft]=useState(null)
  const readSource=()=>{setError('');try{const result=parseProgramText(stripTranscript(text),allExercises(S),S.xunlian.exerciseAliases);setDraft({...result,id:uid(),sourceType:'creator-import',sourceName:sourceName||'用户导入原文',sourceUrl,originalText:text,importedAt:Date.now(),baseRevision:S.xunlian.revision})}catch(e){setError(e.message)}}
  const analyze=()=>runAI(async signal=>{setError('');try{requireAI(S);const catalog=allExercises(S);const result=await createDeepSeek({credential:getCredential,model:S.xunlian.ai.model}).generateStructured('program',{task:generate?'Generate an executable plan using only supplied exercises':'Parse source text; do not invent source parameters',text:stripTranscript(text),context:planningContext(S),exercises:catalog.filter(e=>e.translationSource==='manual'||e.custom).slice(0,120).map(e=>({id:e.id,nameZh:e.nameZh,nameEn:e.nameEn||e.n,equipment:e.eq}))},{signal});const p={...result,id:uid(),sourceType:generate?'ai-generated':'creator-import',sourceName,sourceUrl,originalText:text,importedAt:Date.now(),baseRevision:S.xunlian.revision,days:result.days.map(d=>({...d,exerciseItems:d.exerciseItems.map(e=>{const mapping=mapEntity(e.originalText,catalog,S.xunlian.exerciseAliases);return {...e,...mapping,exerciseId:mapping.selectedExerciseId}})}))};setDraft(p);update(s=>{s.xunlian.drafts.unshift({kind:'program',data:p,at:Date.now()});s.xunlian.drafts=s.xunlian.drafts.slice(0,20)})}catch(e){setError(aiErrorMessage(e))}})
  return <><h2>{t(generate?'AI training plan':'Import training program')}</h2><TextField placeholder={t('Source / creator')} value={sourceName} onChange={e=>setSourceName(e.target.value)}/><TextField placeholder={t('Source URL (optional)')} value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/><TextArea maxLength={60000} placeholder={t(generate?'Describe your training needs':'Paste text or subtitles')} value={text} onChange={e=>setText(e.target.value)}/><input type="file" aria-label={t('Import file')} accept=".txt,.md,.srt,.vtt" onChange={async e=>{const f=e.target.files[0];if(f?.size>300000){setError(t('File too large'));return}if(f)setText(await f.text())}}/><p className="sect-f">{t('Only the text and necessary planning context are sent to DeepSeek after you press Analyze. Review before saving.')}</p>{!generate&&<><p className="sect-f">{t('Explicit text format: Monday / barbell bench press 40kg 3×8 rest 120s. Local parsing preserves written numbers; AI handles free-form text after review.')}</p><Button variant="primary" disabled={busy||!text.trim()} onClick={readSource}>{t('Read source parameters offline')}</Button></>}{error&&<p className="notice">{error}</p>}<Button disabled={busy||!text.trim()} onClick={analyze}>{t(busy?'Analyzing…':'AI Analyze')}</Button>{busy&&<Button onClick={cancel}>{t('Cancel request')}</Button>}{draft&&<Button onClick={()=>{close();useUI.getState().openSheet(done=><ProgramReview initial={draft} close={done}/>)}}>{t('Review program')}</Button>}</>
}
export default function Programs() {
  const S=useStore(s=>s.S),nav=useNavigate(),[params,setParams]=useSearchParams(),[tab,setTab]=useState(params.has('creator')?'creators':'templates'),[search,setSearch]=useState(''),[filters,setFilters]=useState({goal:'',intensity:'',duration:'',body:''})
  const source=params.get('source')||'',category=params.get('category')||'',catalog=useMemo(()=>allExercises(S),[S.customEx]),templates=useMemo(()=>knowledgePrograms(catalog),[catalog])
  const show=p=>useUI.getState().openSheet(close=><ProgramReview initial={p} close={close}/>),enter=(source='',category='')=>setParams({...source&&{source},...category&&{category}})
  const sourceInfo=new Map([...chinaGuides.map(g=>[g.id,{label:g.title,publisher:g.publisher+' · '+g.year,summary:g.summary,url:g.url}]),
    ['acsm-resistance-2026',{label:'ACSM 2026 抗阻训练指南',publisher:'美国运动医学会',summary:'力量、增肌训练量与爆发力原则。'}],
    ['cdc-adults',{label:'成人身体活动指南',publisher:'CDC / 美国成人活动指南',summary:'有氧活动与主要肌群力量训练。'}],
    ['activity-compendium-2024',{label:'2024 活动能耗参考',publisher:'Adult Compendium',summary:'按已加载活动类型整理；MET为人群估计。'}]])
  const matching=templates.filter(p=>matchesProgram(p,filters,search)),sourcePlans=matching.filter(p=>p.sourceGuideId===source),visible=sourcePlans.filter(p=>p.knowledgeCategory===category)
  const sourceIds=[...new Set(matching.map(p=>p.sourceGuideId))],categories=[...new Set(sourcePlans.map(p=>p.knowledgeCategory))],currentSource=sourceInfo.get(source)
  const create=()=>{const days=S.routines.slice(0,7).filter(r=>r.ex.length).map((r,i)=>({weekday:weekdays[i],dayName:r.name,exerciseItems:r.ex.map(e=>({exerciseId:e.id,originalText:EXIDX[e.id]?.nameEn||EXIDX[e.id]?.n||e.id,mappingStatus:EXIDX[e.id]?'exact':'unmapped',sets:e.sets,reps:e.reps,weight:e.weight,durationSec:e.sec,restSec:S.restSec,supersetGroup:e.sg,estimatedFields:[]}))}));show({id:uid(),nameZh:t('My training program'),nameEn:'',sourceType:'user-created',sourceName:'',progression:'off',days:days.length?days:[{weekday:1,dayName:t('Monday'),exerciseItems:[]}]})}
  const back=()=>tab==='creators'?(params.has('courseType')?setParams({creator:params.get('creator')}):params.has('creator')?setParams({}):nav('/plan')):category?enter(source):source?enter():nav('/plan')
  const select=(key,label,options)=><label className="program-filter" key={key}><span>{label}</span><select aria-label={label} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">全部</option>{Object.entries(options).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>
  return <div className="narrow feature-page program-library"><div className="hdr"><button className="iconbtn" aria-label="返回上一级" onClick={back}><Icon name="chevronLeft"/></button><div><h1>{t('Training programs')}</h1><div className="sub">按来源、分类逐层查看训练计划</div></div></div>
    <Segmented value={tab} onChange={value=>{setTab(value);setParams({})}} options={[['templates','Templates'],['creators','博主计划'],['saved','My programs'],['drafts','Drafts']].map(([value,label])=>({value,label:t(label)}))}/>
    {tab==='templates'?<>
      <div className="program-filters">{select('goal','训练目标',goalLabels)}{select('intensity','强度分类',intensityLabels)}{select('duration','单次训练时间',{short:'30 分钟以内',medium:'31–60 分钟',long:'60 分钟以上'})}{select('body','训练部位',bodyLabels)}</div>
      <TextField aria-label="搜索计划或来源" placeholder="搜索计划、运动项目或来源" value={search} onChange={e=>setSearch(e.target.value)}/>
      {(search||Object.values(filters).some(Boolean))&&<Button size="sm" onClick={()=>{setSearch('');setFilters({goal:'',intensity:'',duration:'',body:''})}}>清除筛选</Button>}
      <nav className="program-crumbs" aria-label="知识库层级"><button onClick={()=>enter()}>知识库来源</button>{source&&<><span>›</span><button onClick={()=>enter(source)}>{currentSource?.label||source}</button></>}{category&&<><span>›</span><span>{category}</span></>}</nav>
      <p className="sect-f">符合筛选 {matching.length} / {templates.length} 套。强度为应用建议，时间含热身和组间休息估算，可在计划内调整。</p>
      <section className="program-browser" aria-label={!source?'知识库来源':!category?'来源下的训练分类':'分类下的具体计划'}>
        {!source?sourceIds.map(id=>{const info=sourceInfo.get(id),count=matching.filter(p=>p.sourceGuideId===id).length;return <button className="program-card source-card" key={id} onClick={()=>enter(id)}><h3>{info?.label||id}</h3><p>{info?.publisher}</p><p className="program-meta">{count} 套计划 · 查看分类 <Icon name="chevronRight"/></p></button>}):!category?categories.map(c=><button className="program-card category-card" key={c} onClick={()=>enter(source,c)}><h3>{c}</h3><p className="program-meta">{sourcePlans.filter(p=>p.knowledgeCategory===c).length} 套计划 · 查看具体训练 <Icon name="chevronRight"/></p></button>):visible.map(p=><button className="program-card template-card" key={p.id} onClick={()=>show(p)}><h3>{p.nameZh}</h3><p className="program-meta"><span>每周 {p.days.length} 天</span><span>单次最长约 {p.filters.minutes} 分钟</span><span>{intensityLabels[p.filters.intensity]}</span></p><p className="program-meta">{p.filters.bodyParts.filter(k=>!['upper'].includes(k)).map(k=>bodyLabels[k]).join(' · ')}</p><p className="program-open">查看组次、重量和休息 <Icon name="chevronRight"/></p></button>)}
        {(!source&&!sourceIds.length||source&&!category&&!categories.length||category&&!visible.length)&&<p className="notice">当前筛选下没有计划，请调整筛选或返回其他来源。</p>}
      </section>
      {source&&<details className="program-source-note"><summary>来源要点与适用说明</summary><p>{currentSource?.summary}</p><p className="sect-f">具体动作、星期、组次选择及初始公斤数由应用整理，并非机构发布的固定课程；活动计时不替代专项教学。军体原则不作为普通新手默认强度。</p><a href={templates.find(p=>p.sourceGuideId===source)?.sourceUrl} target="_blank" rel="noreferrer">核对原始来源</a></details>}
    </>:tab==='creators'?<CreatorPrograms catalog={catalog} onShow={p=>show(creatorMappedProgram(p,catalog))} onGenerate={p=>nav('/assistant?creatorPlan='+encodeURIComponent(p.id))} onImport={p=>useUI.getState().openSheet(close=><ImportProgram close={close} initialSource={p}/>)}/>:<Section title={t(tab==='saved'?'My programs':'Drafts')}>{(tab==='saved'?S.xunlian.programs:S.xunlian.drafts.filter(d=>d.kind==='program').map(d=>d.data)).map((p,i)=><Row key={p.id+'-'+i} title={p.nameZh} subtitle={p.sourceName||t(p.sourceType)} value={p.days.length+' '+t('Training days')} accessory="chevron" onClick={()=>show(p)}/>)}</Section>}
    <div className="program-tools"><Button variant="tinted" onClick={create}>{t('Create program')}</Button><Button onClick={()=>useUI.getState().openSheet(close=><ImportProgram close={close}/>)}>{t('Import')}</Button><Button onClick={()=>nav('/assistant')}>AI 对话生成训练与饮食</Button><Button onClick={()=>nav('/review')}>{t('Weekly review')}</Button></div>
  </div>
}
