import { describe,it,expect,vi } from 'vitest'
import { createDeepSeek,normalizeStructuredResult } from './deepseek.js'
import { localIntake } from './intake-fallback.js'
const reply=data=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(data)}}]})})
describe('AI intake compatibility and contract repair',()=>{
  it('accepts eight common object questions without losing their wording',async()=>{const questions=Array.from({length:8},(_,i)=>({id:i,question:'确认条件 '+i}));const fetcher=vi.fn(async()=>reply({questions,summary:null}));const result=await createDeepSeek({credential:async()=> 'synthetic',fetcher}).generateStructured('intake',{});expect(result.questions).toEqual(questions.map(q=>q.question));expect(result.summary).toBe('');expect(fetcher).toHaveBeenCalledTimes(1)})
  it('preserves numbered multiline questions as separate questions',()=>{expect(normalizeStructuredResult('intake',{questions:'1. 有哪些伤病？\n2、 有哪些忌口？'}).questions).toEqual(['有哪些伤病？','有哪些忌口？'])})
  it('sends precise schema issues on repair instead of the field name alone',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(reply({questions:[{answer:'not a question'}]})).mockResolvedValueOnce(reply({questions:['有哪些伤病？']}));const result=await createDeepSeek({credential:async()=> 'synthetic',fetcher}).generateStructured('intake',{});expect(result.questions).toEqual(['有哪些伤病？']);const body=JSON.parse(fetcher.mock.calls[1][1].body);expect(body.messages.at(-1).content).toContain('questions.0');expect(body.messages.at(-1).content).toContain('expected string')})
  it('publishes the actual count/type contract, including coach meal requirements',async()=>{let body;const p=createDeepSeek({credential:async()=> 'synthetic',fetcher:async(_,o)=>{body=JSON.parse(o.body);return reply({questions:['有没有伤病？']})}});await p.generateStructured('intake',{});expect(body.messages[0].content).toContain('"maxItems":12');expect(body.messages[0].content).toContain('"maxLength":600');expect(body.messages[0].content).toContain('当前操作是追问')})
  it('still rejects unusable questions and never relaxes program quantity checks',async()=>{const p=createDeepSeek({credential:async()=> 'synthetic',fetcher:async()=>reply({questions:[42]})});await expect(p.generateStructured('intake',{})).rejects.toMatchObject({code:'schema'});const program={days:[{exerciseItems:[{sets:'three'}]}]};expect(normalizeStructuredResult('program',program)).toBe(program)})
  it('labels local questions as local and asks every required restriction',()=>{const fallback=localIntake();expect(fallback.source).toBe('local');expect(fallback.questions.join('')).toContain('伤病');expect(fallback.questions.join('')).toContain('忌口');expect(fallback.questions.join('')).toContain('洗澡');expect(fallback).not.toHaveProperty('program')})
})
