import { describe,it,expect } from 'vitest'
import { coachProfile,validateBrief,coachTarget,briefFallback,COACH_BRIEF_PROMPT } from './coach-workflow.js'
import { CoachBriefSchema,createDeepSeek } from './deepseek.js'
import { fitPortions,balanceCoachMeals } from './meal-portions.js'
import { dailyTotals,recipeNutrition,scaleNutrition,validatePlanningProfile } from './nutrition.js'
import { recipeCost,budgetRecipes } from './meal-cost.js'
import { eligibleRecipes,validateMeals } from './planning-engine.js'
import { feasibleMenu } from './assistant-plan.js'
import { parseProgramText } from './program-import.js'
import foods from '../data/foods.json'
import recipes from '../data/recipes.json'
const stored={age:24,weightKg:85,heightCm:172,sex:'male',fitnessLevel:'occasional',goal:'lose',activity:1.4,limitations:'无',allergies:'无'}
const schedule={trainingPlace:'gym',availableDays:[1,2,3,5,6],trainingDays:5,trainingDuration:60}
const target={kcal:2200,proteinG:136,fatG:68,carbsG:260},options=eligibleRecipes(recipes,foods,{allergies:'无'}),menu=feasibleMenu(options,foods,target),date='2026-09-28'
describe('brief driven coach',()=>{
  it('uses stored body values without overwriting the schedule or forbidding impact by default',()=>{const p=coachProfile(stored,{...schedule,allergies:'香菜',avoidExercises:'腰部负重'});expect(p.age).toBe(24);expect(p.trainingDays).toBe(5);expect(p.lowImpact).toBeUndefined();expect(p.dislikedFoods).toBeUndefined()})
  it('allows no questions and limits new intake to three, not twelve',()=>{expect(CoachBriefSchema.parse({questions:[],profile:schedule}).questions).toEqual([]);expect(CoachBriefSchema.safeParse({questions:['a','b','c','d'],profile:{}}).success).toBe(false);expect(COACH_BRIEF_PROMPT).toContain('不再追加问题')})
  it('does not demand repeated confirmation and disallows a second question round',()=>{expect(validateBrief({questions:[],profile:schedule},stored,{answered:true}).trainingDays).toBe(5);expect(()=>validateBrief({questions:['再填一下？'],profile:schedule},stored,{answered:true})).toThrow('不重复追问')})
  it('does not silently assign missing body or time values',()=>{expect(()=>validateBrief({questions:[],profile:schedule},{age:null})).toThrow('身体资料');expect(()=>validateBrief({questions:[],profile:{}},stored)).toThrow('单次分钟')})
  it('retains explicit manual nutrition target when profile has not changed',()=>{expect(coachTarget({xunlian:{profile:stored,target}},stored)).toEqual(target);expect(coachTarget({xunlian:{profile:stored,target}}, {...stored,goal:'gain'}).kcal).not.toBe(target.kcal)})
  it('fallback only asks missing necessary data, never creates an unrelated lifestyle checklist',()=>{expect(briefFallback(stored).questions).toHaveLength(0);expect(briefFallback({...stored,allergies:''}).questions).toHaveLength(1)})
  it('provider accepts zero questions and extracted conditions from one sentence',async()=>{const response={questions:[],profile:schedule,summary:'按你提供的五天时间安排',assumptions:[]};const p=createDeepSeek({credential:async()=> 'fixture',fetcher:async()=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(response)}}]})})});expect(await p.generateStructured('brief',{}, {validate:r=>validateBrief(r,stored)})).toEqual(response)})
})
describe('local meal arithmetic',()=>{
  it('keeps negative source-derived nutrients unknown instead of creating invalid intake',()=>{expect(scaleNutrition({kcal:100,carbsG:-.562},2)).toMatchObject({kcal:200,carbsG:null})})
  it('rescales badly sized AI portions using real nutrition instead of rejecting the whole result',()=>{const bad=menu.map(m=>({...m,date,servings:m.servings*.25})),result=balanceCoachMeals({meals:bad},[date],options,foods,{},target,menu,()=> 'id');expect(result.note).toContain('校准');expect(()=>validateMeals(result,[date],options,foods,{},target,()=> 'id')).not.toThrow();expect(dailyTotals(result.snapshots,date).kcal).toBeGreaterThan(1760)})
  it('preserves already valid choices and servings',()=>{const original=menu.map(m=>({...m,date}));expect(fitPortions(original,options,foods,target)).toBe(original)})
  it('cannot repair an invented recipe, excluded ingredient, or missing main meal',()=>{const original=menu.map(m=>({...m,date}));expect(()=>balanceCoachMeals({meals:[{...original[0],recipeId:'invented'},...original.slice(1)]},[date],options,foods,{},target,menu,()=> 'id')).toThrow();expect(()=>balanceCoachMeals({meals:original.slice(1)},[date],options,foods,{},target,menu,()=> 'id')).toThrow()})
  it('labels an incompatible day replaced with a verified fallback and revalidates the result',()=>{const low=options.find(r=>recipeNutrition(r,foods).nutrition.proteinG/recipeNutrition(r,foods).nutrition.kcal<.04);expect(low).toBeDefined();const original=['breakfast','lunch','dinner'].map(slot=>({date,slot,recipeId:low.id,servings:1}));const result=balanceCoachMeals({meals:original},[date],options,foods,{},target,menu,()=> 'id');expect(result.note).toContain('替换');expect(result.snapshots).toHaveLength(3)})
})
describe('explicit constraints and imported prescriptions',()=>{
  it('plans the specified meal count rather than always requiring three meals',()=>{const profile={mealCount:2},day=feasibleMenu(options,foods,target,{profile});expect(day.map(m=>m.slot)).toEqual(['breakfast','dinner']);expect(()=>validateMeals({meals:day.map(m=>({...m,date}))},[date],options,foods,profile,target,()=> 'id')).not.toThrow();const four=feasibleMenu(options,foods,target,{profile:{mealCount:4}});expect(four).toHaveLength(4)})
  it('never invents food prices, and enforces a stated budget when prices exist',()=>{const r=options[0];expect(recipeCost(r,{})).toBeNull();const prices=Object.fromEntries(r.ingredients.map(i=>[i.foodId,1])),p={foodPrices:prices,dailyBudgetCny:1};expect(recipeCost(r,p)).toBeGreaterThan(1);expect(budgetRecipes(options,p).every(x=>recipeCost(x,p)!=null)).toBe(true);const original=['breakfast','lunch','dinner'].map(slot=>({recipeId:r.id,date,slot,servings:1}));expect(()=>validateMeals({meals:original},[date],options,foods,p,null,()=> 'id')).toThrow('预算')})
  it('labels budget as unverified when source prices are missing',()=>{const original=menu.map(m=>({...m,date}));const result=balanceCoachMeals({meals:original},[date],options,foods,{dailyBudgetCny:50},target,menu,()=> 'id');expect(result.note).toContain('预算尚未验证');expect(result.snapshots.every(m=>m.costSnapshotCny==null)).toBe(true)})
  it('rejects invalid planning constraints and price dictionaries before saving or restoring',()=>{expect(()=>validatePlanningProfile({mealCount:9})).toThrow();expect(()=>validatePlanningProfile({foodPrices:{rice:-1}})).toThrow();expect(validatePlanningProfile({mealCount:2,dailyBudgetCny:null})).toMatchObject({mealCount:2})})
  it('enforces vegetarian and cooking-time constraints before candidates go to AI',()=>{const plant=eligibleRecipes(recipes,foods,{dietStyle:'vegan'});expect(plant.length).toBeGreaterThan(2);expect(plant.some(r=>r.nameZh.includes('鸡胸'))).toBe(false);const quick=eligibleRecipes(recipes,foods,{cookingMinutes:10});expect(quick.every(r=>r.prepMinutes<=10)).toBe(true);expect(quick.length).toBeGreaterThan(0)})
  it('repairs a repeated seven-day menu without weakening the weekly repeat limit',()=>{const dates=Array.from({length:7},(_,i)=>'2026-09-'+String(21+i));const original={meals:dates.flatMap(date=>menu.map(m=>({...m,date})))};const result=balanceCoachMeals(original,dates,options,foods,{repeatMeals:3},target,menu,()=> 'id');const counts={};for(const m of result.meals)counts[m.recipeId]=(counts[m.recipeId]||0)+1;expect(Math.max(...Object.values(counts))).toBeLessThanOrEqual(3);expect(result.snapshots).toHaveLength(21)})
  it('retains rep ranges, effort and tempo rather than dropping the upper range',()=>{const p=parseProgramText('周一\n杠铃卧推 40kg 3组×8-12次 休息2分钟 RPE 7 RIR 3 节奏3-1-1-0',[{id:'bench',nameZh:'杠铃卧推'}]);expect(p.days[0].exerciseItems[0]).toMatchObject({weight:40,sets:3,reps:null,repsMin:8,repsMax:12,restSec:120,rpe:7,rir:3,tempo:'3-1-1-0'})})
  it('distinguishes exercise duration from rest duration',()=>{const p=parseProgramText('平板支撑 3组 每组45秒 休息60秒',[{id:'plank',nameZh:'平板支撑'}]);expect(p.days[0].exerciseItems[0]).toMatchObject({durationSec:45,restSec:60})})
})
