import { describe,it,expect } from 'vitest'
import { photoMeal,recordPhotoMeal,replacePhotoPlan,photoFoods } from './food-photo.js'
import { createDeepSeek } from './deepseek.js'
import { emptyXunlian,clone } from './nutrition.js'
import { validateMealSnapshots,backupState } from './xunlian-state.js'
const foods=[{id:'pork',nameZh:'猪肉',nameEn:'Pork',foodType:'raw',translationSource:'manual',sourceRelease:'fixture',nutritionPer100g:{kcal:200,proteinG:20,fatG:10,carbsG:0}}]
const response={status:'identified',nameZh:'肉馅估算',confidence:'low',notes:['不是实测'],ingredients:[{foodId:'pork',grams:100,gramsMin:80,gramsMax:150,basis:'按描述估计，猪肉种类与肥瘦不确定'}]},meta={id:'photo1',date:'2026-10-01',slot:'lunch',description:'三个小包子的肉馅'}
const result=()=>photoMeal(response,foods,meta)
const state=()=>({xunlian:emptyXunlian()})
describe('photo intake and explicit plan replacement',()=>{
  it('computes calories locally and preserves estimation range, assumptions and source',()=>{const m=result();expect(m.nutritionSnapshot.kcal).toBe(200);expect(m.photoAnalysis).toMatchObject({kcalMin:160,kcalMax:300,confidence:'low'});expect(m.estimated).toBe(true);expect(()=>validateMealSnapshots([m])).not.toThrow()})
  it('asks for missing detail without inventing or recording intake',()=>{expect(photoMeal({...response,status:'needs_detail',ingredients:[]},foods,meta)).toBeNull();expect(()=>photoMeal({...response,status:'needs_detail'},foods,meta)).toThrow()})
  it('rejects invented food IDs, duplicates, negative or inverted estimates and invalid dates',()=>{for(const ingredients of [[{...response.ingredients[0],foodId:'invented'}],[...response.ingredients,...response.ingredients],[{...response.ingredients[0],gramsMin:120}],[{...response.ingredients[0],gramsMax:-1}]])expect(()=>photoMeal({...response,ingredients},foods,meta)).toThrow();expect(()=>photoMeal(response,foods,{...meta,date:'2026-02-30'})).toThrow()})
  it('records once, preserves original plan until explicit replacement and excludes photos from backups',()=>{const s=state(),m=result();s.xunlian.meals=[{id:'old',date:m.date,slot:m.slot}];recordPhotoMeal(s,m);recordPhotoMeal(s,m);expect(s.xunlian.logs).toHaveLength(1);expect(s.xunlian.meals[0].id).toBe('old');expect(JSON.stringify(backupState(s))).not.toContain('data:image');expect(JSON.stringify(backupState(s))).not.toContain('imageDataURL')})
  it('replaces only the selected meal, preserves actual intake and saves a plan snapshot for undo',()=>{const s=state(),m=result();s.xunlian.meals=[{id:'old',date:m.date,slot:m.slot},{id:'other',date:m.date,slot:'dinner'}];recordPhotoMeal(s,m);replacePhotoPlan(s,m,['old']);expect(s.xunlian.logs).toHaveLength(1);expect(s.xunlian.logs[0].plannedMealId).toBe('photo-plan-photo1');expect(s.xunlian.meals.find(m=>m.id==='other')).toBeDefined();expect(s.xunlian.snapshots[0].meals[0].id).toBe('old');s.xunlian.meals=clone(s.xunlian.snapshots[0].meals);expect(s.xunlian.logs).toHaveLength(1)})
  it('rejects stale replacement before changing plan or history',()=>{const s=state(),m=result();recordPhotoMeal(s,m);s.xunlian.meals=[{id:'changed',date:m.date,slot:m.slot}];expect(()=>replacePhotoPlan(s,m,['old'])).toThrow('已改变');expect(s.xunlian.snapshots).toHaveLength(0)})
  it('rejects invalid photo ranges in restored records',()=>{const m=result();m.photoAnalysis.kcalMax=100;expect(()=>validateMealSnapshots([m])).toThrow()})
  it('sends image only in user messages via the supported model and validates before returning',async()=>{let payload;const p=createDeepSeek({credential:async()=> 'fixture',fetcher:async(u,o)=>{payload=JSON.parse(o.body);return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify(response)}}]})}}});await p.generateStructured('foodPhoto',{description:'食物'},{imageDataURL:'data:image/jpeg;base64,YQ==',validate:r=>photoMeal(r,foods,meta)});expect(payload.model).toBe('deepseek-flash');expect(payload.messages[0].content).not.toContain('data:image');expect(payload.messages[1].content[1].type).toBe('image_url');expect(payload.messages[1].content[0].text).toContain('食物')})
  it('does not submit unsupported or missing photos and cancels before request',async()=>{let calls=0;const p=createDeepSeek({credential:async()=> 'fixture',fetcher:async()=>{calls++;throw new Error('should not call')}});await expect(p.generateStructured('foodPhoto',{})).rejects.toMatchObject({code:'input'});await expect(p.generateStructured('foodPhoto',{}, {imageDataURL:'https://example.com/photo.jpg'})).rejects.toMatchObject({code:'input'});const controller=new AbortController();controller.abort();await expect(p.generateStructured('foodPhoto',{}, {signal:controller.signal,imageDataURL:'data:image/jpeg;base64,YQ=='})).rejects.toMatchObject({code:'cancelled'});expect(calls).toBe(0)})
  it('only offers complete local food nutrition to recognition',()=>{expect(photoFoods([...foods,{...foods[0],id:'unknown',nutritionPer100g:{kcal:null}}])).toHaveLength(1)})
})
